### ISSUE TITLE
ClassicThemeRestorer don't include the license file

### ISSUE THREAD

**Issue by puntogil** [Aris-t2/ClassicThemeRestorer#111]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
All source files are without license headers. 
Please, add license headers in those files where is missing
Thanks in advance
Regards

**Comment by Aris-t2** [comment]
Why and what for?

CTR is realeased under Mozilla Public License, version 2.0: http://www.mozilla.org/MPL/2.0/

**Comment by RobertZenz** [comment]
Despite that it is licensed under a very permissive license, it is still licensed, and that needs to be made clear. This is necessary for two reasons:

 1. Not licensed code, read code not licensed under a certain license or missing any license information *has to be assumed* to be not licensed. Which means that it defaults to "all rights reserved" which pretty much means "don't touch, and sometimes better don't look at it". Adding a license file and header to the source makes this absolutely clear without any question.
 2. Currently the repository does not contain *any* license information. The only site containing this info is the AMO page. So, let's assume that the AMO page goes away for some reason, it can not be verified that the code in this repository is licensed under MPL, which means point 1 gets into effect.

Adding the license information does remove *any* ambiguity and clearly indicates your intentions.

**Comment by Aris-t2** [comment]
Allright, I have added a copy of "Mozilla Public License 2.0" to CTRs root on Github.
