### ISSUE TITLE
Interface problem with Firefox Nightly 

### ISSUE THREAD

**Issue by Zefling** [Aris-t2/ClassicThemeRestorer#115]
Some elements of the interface are graphically unstable, like this :
http://ikilote.net/Galeries/Autres/Divers/Nightly-Glishes.png

I write a bug on bugzilla : https://bugzilla.mozilla.org/show_bug.cgi?id=1224736

**Comment by Aris-t2** [comment]
Are you using a new Firefox profile with only CTR installed and this happens? Does without CTR everything look fine on a new Firefox profile ?

So far I have tested CTR on Linux Mint (KDE) and Ubuntu and I never saw such glitches.
Have you tried to disable "hardware acceleration" in your Firefox settings?

**Comment by Zefling** [comment]
Sorry, I think I cause by a corrupt profile.
