### ISSUE TITLE
title bar - tabs on top

### ISSUE THREAD

**Issue by beppe61** [Aris-t2/ClassicThemeRestorer#116]
If enable "tabs on bottom", some new windows miss the title bar, so is not ossible move the new window.
i.e.
On this site
http://kajamira.blogspot.it/
if you open a link named  "Commenti" the new window  has not the title bar, and you can not move the window

![missing-title-bar](https://cloud.githubusercontent.com/assets/15850006/11165448/c0339d1a-8b0f-11e5-8f5d-f69de2d9da0a.jpg)

**Comment by Aris-t2** [comment]
Are you using "tabs not on top v2"? If yes, switch to  "tabs not on top v1".
v2 is meant for some rare cases and some complete themes, but not for avarage usage.

**Comment by beppe61** [comment]
With  CTR 1.4.3 beta 17 the issue seems fixed.
Thanks a lot

**Comment by Aris-t2** [comment]
Good. Official 1.4.3 release is not that far away anymore.
