### ISSUE TITLE
Minor typo on Line 408 overlay.js

### ISSUE THREAD

**Issue by InternalError503** [Aris-t2/ClassicThemeRestorer#129]
Hi @Aris-t2 

There is a minor typo [here](https://github.com/Aris-t2/ClassicThemeRestorer/blob/master/xpi/content/overlay.js#L408)  with the word enabled.

```javascript
// TreeStyleTabs add-on works better with tabs not on top, so this is eanbled on reset/first run
			  AddonManager.getAddonByID('treestyletab@piro.sakura.ne.jp', function(addon) {
```

**Comment by Aris-t2** [comment]
Thanks. I bet there are more typos in CTRs files. ;-)

**Comment by InternalError503** [comment]
Np, I am terrible with typos too :)

**Comment by Aris-t2** [comment]
As long as they are only inside some comments only a few people ever see them.
Inside latest beta that one is fixed. ;-)
