### ISSUE TITLE
Classic search bar is not triggered by mouse click on the magnifying glass icon

### ISSUE THREAD

**Issue by schurz** [Aris-t2/ClassicThemeRestorer#132]
Hello,
I installed ClassicThemeRestorer to restore the classic search bar and it works really good - thanks a lot.
One deviation I noticed is that I can only trigger the search by pressing return and not by clicking on the magnifiying glass.

FF 43.0 32bit / CTR 1.4.3.1-signed
Reproduced with Windows 7 and Windows XP

**Comment by Aris-t2** [comment]
This issue does not occur for me on Win7-10 with Fx43-46.

Are you using any add-on, that modifies the search bar?
Could you test CTR with a new profile?

**Comment by schurz** [comment]
It worked as expected with a new profile.
I tried deactivating some addons and it seems the combination of Tab Mix Plus and Classic Theme Restorer causes this misbehavior.
It can be reproduced by creating a new profile and installing both CTR + TMP.
If TMP addon is enabled, the mouse click is not processed anymore.

**Comment by Aris-t2** [comment]
TabMixPlus causes this bug. It even occurs on a new profile without CTR installed.
Type anything into search bar and hit the arrow "->". Nothing happens.

This bug is fixed in TMPs developer builds:
https://addons.mozilla.org/addon/tab-mix-plus/versions/
