### ISSUE TITLE
Classic search bar focus order

### ISSUE THREAD

**Issue by schurz** [Aris-t2/ClassicThemeRestorer#133]
If the text cursor is in the URL address text field, I need to `<TAB>` twice to get the focus of the search text field and have the current text marked.
The first `<TAB>` seems to focus the search provider selection, since I can open the menu with `<ALT>`+`<DOWN>`.

If I remember correctly, this was different, I don't have a reference installation to check right now.

**Comment by Aris-t2** [comment]
Indeed it was different. Using Fx42 code on Fx43+ causes this, but I have no idea why.

**Comment by Aris-t2** [comment]
Could you test this dev build?
https://www.dropbox.com/s/50mqr4h5t4detzy/CTR_v1.4.5r34.xpi?dl=0

**Comment by schurz** [comment]
Thanks for your quick response!

I checked the dev build with FF44.0a2 64bit and compared against an older installation with  browser.search.showOneOffButtons = false

Focus order and text selection work identically. To change the focus after entering some text in the URL bar enforces to hit <ESC> to get rid of that "search with google" element, but I guess this is another FF feature.

I have noticed some differences in keyboard control that may be linked with the focussed elements.
In the old FF installation with focus in the search text field, I switch between the search history (or proposed search terms if enabled) with <UP> and <DOWN>. If I do this while holding <ALT> I switch between the search providers. With CTR classic search only the first variant is possible.

**Comment by Aris-t2** [comment]
I guess you wanted to say, you are using CTRL and ALT keys, right? And only CTRL key works so far, right?
The ALT key navigation through the search engine list will be fixed on next beta.

**Comment by schurz** [comment]
I updated the comments, didn't realize I have to escape &lt; and &gt;.
Actually I didn't know the `<CTRL>` variant at all, always switched with `<ALT>`.
Even more laziness possible, thanks ;-)

**Comment by Aris-t2** [comment]
Install 1.4.5 beta 7. ALT key should work fine now.
https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by schurz** [comment]
Works perfectly!
