### ISSUE TITLE
Integrate Organize Search Engines into CTR

### ISSUE THREAD

**Issue by KOLANICH** [Aris-t2/ClassicThemeRestorer#146]
Organize Search Engines is the addon allowing to make Search Engines menu a tree.
https://code.google.com/p/organize-search-engines/source/browse/

Some time ago it was on AMO, but now it [isn't there](https://addons.mozilla.org/firefox/addon/organize-search-engines/).

It can be fine to integrate it into CTR.

**Comment by Aris-t2** [comment]
That add-on is not compatible with the new search API and has to be rewritten from the scratch. Unfortunately CTR is not about restoring discontinued add-ons, sorry.

**Comment by RAWRR** [comment]
@Aris-t2

Old Search. Old Search Fixed2, and CTR all implement the old drop-down search function well. The only thing missing is folders - even separators are still present AFAIK, just not available in search settings to the user.

Isn't this just a case of a missing class (folders) that has to be restored?

**Comment by Aris-t2** [comment]
See my previous post, sorry.

**Comment by RAWRR** [comment]
@Aris-t2

No problem, thanks for the reply.

@KOLANICH

Found this: https://github.com/Baton34/organize-search-engines

Which works at least up to 45, which is an ESR release so that should hold people over for awhile.

**Comment by Aris-t2** [comment]
Good to know. So it still is possible to recreate those features, great.
The version 1.93 also works in Firefox 49 Nightly. A button related glitch on some OS configurations increases searchbars height, what can be fixed by using this css code:
```css
.searchbar-engine-button{
  -moz-appearance: none !important;
  box-shadow: unset !important;
  border: unset !important;
}
```

**Comment by RAWRR** [comment]
Awesome! Submit a PR over there? It isn't abandoned, they just responded to me today.

**Comment by KOLANICH** [comment]
@RAWRR, thank you.
