### ISSUE TITLE
FIrefox 44 and nav-bar buttons

### ISSUE THREAD

**Issue by beppe61** [Aris-t2/ClassicThemeRestorer#152]
In the navigation bar, if "icon+text" enabled,  button's width is fixed, and texts under icons are truncated, (the same happens with "icon+text v.2", "icon+text v.3" or "icon+text v.4" options).
- Classic Theme Restorer v.1.4.6.1 (issue also in v. 1.4.7.x beta)
- Firefox 44
- Windows 7 ultimate (64bit)

**Comment by Aris-t2** [comment]
Install CTR 1.4.7beta7
https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by beppe61** [comment]
Ok, issue fixed.
Thanks

**Comment by Aris-t2** [comment]
Fixed on 1.4.7.
