### ISSUE TITLE
#UITourTooltip is misaligned

### ISSUE THREAD

**Issue by magicp-github** [Aris-t2/ClassicThemeRestorer#166]
#UITourTooltip is misaligned.

My environment...
- Firefox 44.0.2
- CTR 1.4.8
- Windows 10

![tour-ui-tracking-protection](https://cloud.githubusercontent.com/assets/13914314/13195809/a75d26bc-d7fe-11e5-80a8-5159874ee55b.png)

**Comment by Aris-t2** [comment]
Test latest dev build: 1.4.9 beta 3
https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by magicp-github** [comment]
It works fine! Thank you for your prompt action.
