### ISSUE TITLE
Add support for settings sync

### ISSUE THREAD

**Issue by shmerl** [Aris-t2/ClassicThemeRestorer#173]
It would be great to support syncing settings using Mozilla Sync. It simplifies keeping browsers UI consistent across multiple computers.

**Comment by Aris-t2** [comment]
Optional Sync support is part of CTR for a while now.

CTR preferences window > Settings button > Add to Sync
![1](https://cloud.githubusercontent.com/assets/6013569/13616983/afc3965c-e57c-11e5-8029-999fd86376bc.png)

**Comment by shmerl** [comment]
Ah, thanks. Is there a way to see that it's syncing it already? Add to sync is somewhat confusing. Maybe some checkbox style setting would be more clear?

**Comment by Aris-t2** [comment]
Firefox and Sync work like this:
- add-on preference "addonname.prefxyz00X" in about:config
- preference "addonname.prefxyz00X.sync" in about:config
- Sync feature reads which "addonname.prefxyz00X.sync" pref has to be synced

'Add to Sync' and 'Remove from Sync' only target "addonname.prefxyz00X.sync" preferences currently available in CTR. Once a new preference is added 'Add to Sync' has to be selected again.

Adding this as an alwaya active preference would double the amount of available CTR prefs in about:config, but only a tiny minority uses Sync and I don't want everybody having about:config area filled with prefs probably never get used.

For one time preference transfers the export/import feature is also a nice way without using the Mozillas online accounts.
