### ISSUE TITLE
[Feature request] Add option to hide identity-icon

### ISSUE THREAD

**Issue by 5t3f4n** [Aris-t2/ClassicThemeRestorer#177]
Would like to be able to hide the new identify-icon (chrome://browser/skin/identity-icon.svg) that appears int he URL bar in Firefox 45.

Would probably make sense to include the option in "Location bar (2)" by the padlock options.

**Comment by Aris-t2** [comment]
CTR 1.4.9 (final/beta) offers an option to override the i-icon with a globe icon (see Location bar 2 category).

It is possible to completely hide/remove identity icon, but this move will cause and ugly/broken identity box appearance for websites without security icons. Further more hiding security icons with CTR is possible, so hiding both will also create an ugly identity box for some secure connections.

Test is for yourself in Stylish using this code:
```
/*AGENT_SHEET*/
#identity-icon {
  display: none !important;
}
#connection-icon {
  -moz-padding-start: 0 !important;
  -moz-margin-start: 0 !important;
}
```
![1](https://cloud.githubusercontent.com/assets/6013569/13703170/34a5122e-e794-11e5-9c9d-478f203e00f2.png)

**Comment by Aris-t2** [comment]
1.5.0beta1 is now on AMO and offers the mentioned option for some cases.

**Comment by 5t3f4n** [comment]
Trying out 1.5.0beta1 from AMO right now and **http**://example.org/ shows the i/globe and **https**://example.org/ shows the padlock only. This feels even better than hiding it always since it makes the UI more consistent and makes sure there are no padding issues etc. Thank you.
