### ISSUE TITLE
[TESTING] "Old search - Clear searchbox after search" is not working

### ISSUE THREAD

**Issue by ramiresto** [Aris-t2/ClassicThemeRestorer#194]
I am using Firefox latest version and ClassicThemeRestorer latest version.

The option in General UI-->Old search-->Clear searchbox after search is not working.

**Comment by Aris-t2** [comment]
Works fine here up to latest Fx48 Nightly.
Which OS and Firefox version are you using?
What other add-ons are active?

- create a new Firefox profile
- install CTR 1.5.0 or 1.5.1 beta 8
- make sure no other add-ons are installed
- test again

**Comment by ramiresto** [comment]
I have Firefox 45 and CTR 1.5.0

I resolve the issue with CTR 1.5.1 beta 8.
