### ISSUE TITLE
Switch tabs with mouse on top of the window

### ISSUE THREAD

**Issue by nicram6667** [Aris-t2/ClassicThemeRestorer#195]
In the latest version of FF beta (47) and Nightly (49) when you move your mouse on top of the window and try to switch to other card/open a new one with MMB, nothing happens. You have to lower the cursor by at least 1 pixel for the click to be detected. Very frustrating. The problem disappears after turning CTR off, but how can one use firefox without it on. I use the australis tabs but it happened on all tabs settings and changing other settings did not get rid of this problem, though I didn't check all of them.
I'd really appreciate any help, thanks!

**Comment by Aris-t2** [comment]
Which OS and OS theme are you using?
Is CTRs application button active? If yes, which one?
Does this problem occur on a new profile with only CTR installed?

Post here to link to a screenshot of your maximized window.

**Comment by nicram6667** [comment]
I'm on Win 10. I installed CTR on another, clean profile, imported my settings and the problem seems to have disappeared. Though even after diasbling all other addons on my default profile the problem persists. Guess there's something wrong with my profile :/ I'll have to create a new one ...again. Weird that it occured only after updating so i didn't think that the problem is on my end. Anyway, thanks for such a quick answer and sorry for the false alarm ;)

**Comment by Aris-t2** [comment]
Good to hear you could sort things out. I will close this issue.
