### ISSUE TITLE
Firefox Tour stops in introduction when CTR is enabled

### ISSUE THREAD

**Issue by magicp-github** [Aris-t2/ClassicThemeRestorer#206]
Steps to reproduce:
1. Start any versions Firefox with a new profile
2. Enable CTR v1.5.1
3. Start "Firefox Tour".  menubar > Help > Firefox Tour

Firefox Tour stops in introduction because UITourTooltip is not displayed.

Could you please fix this? Thank you in advance.

regards,
magicp

**Comment by Aris-t2** [comment]
I will try to fix it on next beta.

**Comment by Aris-t2** [comment]
Check 1,5,2 beta 7: https://addons.mozilla.org/addon/classicthemerestorer/versions/1.5.2beta7

**Comment by magicp-github** [comment]
Firefox Tour works on 1.5.2 beta 7 !!
Thanks for your excellent work.
