### ISSUE TITLE
[Feature request] Old style for location bar results, disable switch to tab, visible alltabs button [SOLVED]

### ISSUE THREAD

**Issue by q1k** [Aris-t2/ClassicThemeRestorer#225]
OK, so recently I switched back to firefox and I had to update the browser. I immediately noticed a bunch of different things in it (apart from the stupid australis theme), and most of those can be taken care of with ClassicThemeRestorer and ClassicToolbarButtons.

What I would like to see implemented is to bring back the following things:
1. the search results styles like in the old firefox (hits marked with bold and italic and each result separated with a line). I explained this with screenshots [in this thread](http://forums.mozillazine.org/viewtopic.php?f=8&t=3009791).
2. another change in the location bar, please add disable 'switch to tab' option.
3. and bring back 'list all tabs button' at the end of the tabs toolbar. (this can be done with another addon, but I wouldn't want to use too many addons).

_
CTR addon version 1.5.3
Firefox version 45

**Comment by Aris-t2** [comment]
1. Were those ui and features present in Firefox 4-28? Mozilla heavily changed location bar for Firefox 48+ and I'm still tweaking its appearance, so no other ui mods for now. Your screenshot showed WinXPs location bar anyway, not the one Windows 7 offers now or offered in Fx 4-28. Have you tried "Firefox 2" full themes? One of them might offer what you are looking for.

2. Not quite sure what you mean by this, but maybe the preferences "about:config>browser.tabs.loadInBackground" and "about:config>browser.sessionstore.restore_on_demand" are something for you.

3. I can add an option for that, but atm you can also add this code to userChrome.css or a Stylish style
```css
#alltabs-button{
  visibility: visible !important;
}```

**Comment by q1k** [comment]
1. I'm pretty sure that was there in firefox 14

2. That's not what I mean.
[Here's an addon](https://addons.mozilla.org/en-US/firefox/addon/switch-to-tab-no-more/) that does that. But again, I wouldn't want to use separate addons for every little thing.
If you can add these that would be great

**Comment by q1k** [comment]
As for no.3, with the addon I gave above and the 2 classic restorer addons instead of it being an arrow, it becomes 4 dots like the 'group tabs' icon.

I'll post a picture in a minute. I just need to get to my laptop.

**Comment by Aris-t2** [comment]
1. You are right, Firefox 14 offered that ui by default without themes, just checked myself. However there are no plans to add that ui to CTR.
Here is how the results look in Firefox 48 by default:
http://i.imgur.com/zP6Ntv6.png
and here is what CTR offers:
http://i.imgur.com/5GOxYU7.png

2. You do not need a "disable switch to tab" add-on or CTR option, because Firefox offers an option to disable it by default: Options > Privacy > Location bar > Open tab
Uncheck it and there won't be any "switch to tab" entry in your results.

3. You have selected  'Classic Toolbar Buttons' add-ons 'Firefox 2 or 3 toolbar button icon' options. They replace the arrow icon with the ones you see, although that icon may not be exactly what was in Firefox 2 or 3.

**Comment by q1k** [comment]
1. Well that's unfortunate...

2. Oh, I didn't realize that, thanks for that. But for how long will we have that there until they decide to remove it, much like lots of other options like the 'group tabs', 'bookmark all tabs' in the main menus, 'tabs on bottom' etc.

3. So any chance to force that icon? If I remember correctly, it was just an arrow in ff3 as well.

**Comment by Aris-t2** [comment]
1. Too many changes there right now on upcomming Firefox builds. Maybe one day in the future.

2. There are other ways of hiding it, If they remove it. Till then the option is usable.

3. If you keep using CTB, this code will replace the icon with a dark one, but not the old gray one:

Fx3 one
![1](https://cloud.githubusercontent.com/assets/6013569/16081260/15e394d6-330d-11e6-88ae-c496a2c7a8ed.png)

Dark one
![toolbarbutton-dropdown-arrow](https://cloud.githubusercontent.com/assets/6013569/16081303/341d539c-330d-11e6-96c9-cd93d3e04708.png)


```css
#TabsToolbar #alltabs-button:not([customizableui-areatype="menu-panel"]) image{
  list-style-image: url("chrome://cstbb-extension/content/icons/toolbarbutton-dropdown-arrow.png") !important;
}```

**Comment by q1k** [comment]
Thanks for the reply
One problem with the style though.
The arrow changes the undo closed tab icon too:
without style: https://s33.postimg.org/bvffpragf/image.png
with style: https://s33.postimg.org/cjoa8p967/image.png

**Comment by Aris-t2** [comment]
```css
#TabsToolbar #alltabs-button:not([customizableui-areatype="menu-panel"]) > .toolbarbutton-icon{
  list-style-image: url("chrome://cstbb-extension/content/icons/toolbarbutton-dropdown-arrow.png") !important;
}
```

**Comment by q1k** [comment]
Thanks for that,
Keep up the good work. 😄

**Comment by Aris-t2** [comment]
![1](https://cloud.githubusercontent.com/assets/6013569/16155383/7323fdfe-34af-11e6-9668-cc8af533ed7e.png)

**Comment by q1k** [comment]
Now the only thing needed is the line separator, and List-all-tabs custom icon option. :+1:

**Comment by Aris-t2** [comment]
Customizing all tabs icon is not part of what CTR does, besides making is visible. ;-)

The code to add separators between results:
```css
panel[type="autocomplete-richlistbox"] richlistitem:not(:last-of-type),
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"] richlistitem:not(:last-of-type) {
  border-bottom: 1px solid grey !important;
}
```

**Comment by q1k** [comment]
how about in CTB?
do you think you can add the list-all-tabs button to be an arrow?

**Comment by Aris-t2** [comment]
Well, it is an arrow, if you keep the default icon settings. ;-)
So if you are asking whether I will add an option to revert another active option for one icon or not, I must say no. The given css code above should be enough.

**Comment by q1k** [comment]
Well in CTB, I have selected Firefox 3 (alt) main icons. But the list-tabs button becomes 4 dots instead of it staying as an arrow.

**Comment by Aris-t2** [comment]
I know, thats what CTB does on purpose.
My comment 5 days ago offers a workaround where you can use css code in Stylish to override it: https://github.com/Aris-t2/ClassicThemeRestorer/issues/225#issuecomment-226269250

**Comment by q1k** [comment]
> thats what CTB does on purpose
Why?
Firefox 3 wasn't like that.

**Comment by Aris-t2** [comment]
Because the button does not have this ui anymore in Fx4+ and the icon looks too boring and pallid.

![1](https://cloud.githubusercontent.com/assets/6013569/16081260/15e394d6-330d-11e6-88ae-c496a2c7a8ed.png)

Why are we stillk discussing this? The given code above lets you revert the icon.
