### ISSUE TITLE
Tab toolbar height on windows 10 with appbutton (icon only) modes.

### ISSUE THREAD

**Issue by InternalError503** [Aris-t2/ClassicThemeRestorer#226]
@Aris-t2 

Unfortunately i am having issues resolving this one myself otherwise this would have been a pull request sorry.

The issue appears from 46.0.1 to 47.0 with appbutton modes:
- Button on Firefox titlebar (icon only)  **appbutton_v2io**
- Button on Firefox titlebar (icon only) (v2)  **appbutton_v2io2**

Extra pixels appear above the tabs and they are no longer plush with the window.

This affects the following tab styles:
-  Firefox default (Curved tabs) **tabs_default**
- Square tabs (classic) **tabs_squared** 
- Square tabs (classic) (v2) **tabs_squaredc2** 
- Square tabs (australized) **tabs_squared2** 
- Square tabs (australized) (v2) **tabs_squared2c2** 
- Curved tabs (alternative) **tabs_curved**
- Curved tabs (alternative aero) **tabs_curvedall**

Firefox 46.0 tab toolbar spacing normal.
![ctr-46 0 1](https://cloud.githubusercontent.com/assets/2867549/16063901/15d1bed2-32e0-11e6-83b2-dac098610bfd.JPG)

Firefox 47.0 tab toolbar spacing issue.
![ctr-47 0](https://cloud.githubusercontent.com/assets/2867549/16063909/25a45a7c-32e0-11e6-8049-0ca5620bf532.JPG)

Here preference export for easy testing.
http://pastebin.com/EVExGM8t

For additional reference, These were 2 patches i scrapped as they only partially worked.
[Test fix (1)](https://github.com/InternalError503/CyberCTR/commit/9eee119db6e505a9a00bdc834d9a124c74ad02e3)
[Test fix (2)](https://github.com/InternalError503/CyberCTR/commit/05ff9f42cf5357620f4ac990f7c4732419740437)

**Comment by Aris-t2** [comment]
I will look into it.

This does only happen on Windows 10 with Fx47+, if tab height values are below 28px, right?

**Comment by InternalError503** [comment]
> This does only happen on Windows 10 with Fx47+, if tab height values are below 28px, right?

I have not tested it on windows 8.1, But currently _affects windows 10_, This happens regardless of the tab height setting in **Tabs (1)** and **Reduce space above toolbar (if possible)** has no effect.

If you enable **Hide tabs toolbar with only one visible tab** then when more then one tab is open the space above the tabs no longer appears with **Square tabs (classic) (v2)** or **Curved tabs (alternative)** but on the others roughly a 2 pixel space.

**Hide tabs toolbar with only one visible tab**  Square tabs (classic)
![ctr-hidewhenonetabspace](https://cloud.githubusercontent.com/assets/2867549/16078089/11ebead0-3340-11e6-8f2d-16d418f10896.JPG)

**Hide tabs toolbar with only one visible tab** Square tabs (classic) (v2)
![ctr-hidewhenonetabnospace](https://cloud.githubusercontent.com/assets/2867549/16078103/22ab649a-3340-11e6-883b-8648274859ea.JPG)

**Comment by Aris-t2** [comment]
I could tweak a few things, but they are still not perfect.

Appbutton (text/icon, v1/v2) should now work fine with classic tabs v1/v2.

**Hide tabs toolbar with only one visible tab** however is buggy. If it is active and the **reduce hiding delay** option is active too, Firefox adds a gap above tabs, when browser is started in maximized mode. If the browser is started in normal window mode and gets maximized afterwards or if  **reduce hiding delay** option is disabled, there is no gap above tabs toolbars.

The culpit is the **reduce hiding delay** option, If it is active, tabs toolbar gets collapsed via
**document.getElementById("TabsToolbar").style.visibility = 'collapse';**
If it is not active, via
**document.getElementById("TabsToolbar").collapsed = true;**

The first one makes the toolbar not to appear on startup, while the second one shows it for a split second before it gets hidden.

**Comment by InternalError503** [comment]
@Aris-t2 looks like you nailed this one. :+1:

**Comment by Aris-t2** [comment]
@ InternalError503 

This is unrelated to the above problem.

{offtopic}
Is there a way to pm you or write you an email?

Anyway, a Cyberfox user, whose English is not well enough to contact you through official support channels, asked me to look into an issue with my add-on "Add-on Manager - Version Number" where no version number is displayed when showing add-ons manager in sidebar (All-In-One Sidebar add-on). CTR uses the same code and so does CyberCTR, so there might be an issue in CyberCTR/Cyberfox, because the version number is visible in Firefox + CTR + AIOS.
{/offtopic}

**Comment by InternalError503** [comment]
@Aris-t2 

I hope its ok posting this here being unrelated.

{offtopic}
There are 2 main points for contact:
- [Cyberfox website](https://cyberfox.8pecxstudios.com/contact-us/)
- [Support forums](https://8pecxstudios.com/Forums/index.php)

For non browser related:
- [8pecxstudios](https://8pecxstudios.com/contact-us)

The contact form is email support, It internally tags and notifies me of a report as sending directly to
my support email is not tracked by the script and may go unanswered.

Cyberfox kept the code mozilla removed for the version number to display in addon-manager, The code in CTR to add it back is actually disabled in CyberCTR, If i am understanding correctly the user is having issue with the version number showing after a certain screen size as in:
`/toolkit/mozapps/extensions/content/extensions.css` 
I have a method that hides the version number when the window is a smaller size.

```css
/* Hacky method for smaller window size with addon version */
@media screen and (max-width: 850px) {
	.version{
		display: none;
	}
}
```
Thank you for letting me know, I will look at adding a solution for this in the mean time the user could add this to stylish.
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("about:addons") {
.version{
		display: inline;
	}
}
```
{/offtopic}
