### ISSUE TITLE
"Classic image appearance on white background" not working for some images

### ISSUE THREAD

**Issue by sfaisal2005** [Aris-t2/ClassicThemeRestorer#245]
I'm using latest CTR beta (v1.5.5beta9) with Firefox 47.0.1 on Windows 7.

In CTR > General UI (2), I have checked "Classic image appearance on white background" option. It restores classic white background and left alignment for most images on the web. But I've bumped into some images lately that are still shown on black background and centered alignment. Here's a screenshot:

![2016-07-27 2](https://cloud.githubusercontent.com/assets/13907697/17173394/705225e2-541c-11e6-978a-96e553abce37.png)

Here are some links to such images:

[Image 1](https://tpc.googlesyndication.com/simgad/11943154183106956145)
[Image 2](http://vignette1.wikia.nocookie.net/naruto/images/3/36/Naruto_Uzumaki.png/revision/latest/scale-to-width-down/300?cb=20160107083821)
[Image 3](http://ibdp.huluim.com/video/12816667?size=960x540)

I've used another add-on called [Old Default Image Style](https://addons.mozilla.org/en-US/firefox/addon/old-default-image-style/) separately to check for the same issue but it didn't have problem restoring the classic appearance for these images.

**Comment by Aris-t2** [comment]
Unfortunately CTRs option only checks for direct image links
![1](https://cloud.githubusercontent.com/assets/6013569/17178652/8fe57bb2-5416-11e6-9654-0f19aeca713e.png)
and not for obfuscated like this:
![2](https://cloud.githubusercontent.com/assets/6013569/17178658/9428337c-5416-11e6-8de4-708126e584b3.png)
![3](https://cloud.githubusercontent.com/assets/6013569/17178659/945c4d92-5416-11e6-8d28-c0b68a2644de.png)

Old Default Image Style add-on works entirely different.

**Comment by Aris-t2** [comment]
I have added a sub option "Classic image appearance on white background (v2)", that acts more aggressive. It will work with all your example pages, but it also may break some html sites, that are not properly made.

**Comment by sfaisal2005** [comment]
Thanks for taking time to come up with a solution. The new sub-option is working fine so far.
