### ISSUE TITLE
Please clarify copyright for files in xpi/content/images/

### ISSUE THREAD

**Issue by spwhitton** [Aris-t2/ClassicThemeRestorer#247]
For the sake of the Debian packaging of classic-theme-restorer, please help me clarify the copyright status of the files in `xpi/content/images/`.

1. Which of the files did you create for this project, and which of them were extracted from old releases of Firefox?

2. Were any of the files generated from `.svg` source files?  If you wanted to modify any of the icons, would you look to the `.svg` file or directly modify the `.png`?  Debian requires a copy of all files in the "preferred format for modification".

Thank you for your help with this -- I hope that we can keep classic-theme-restorer in the Debian archive and in the upcoming Debian Stretch release.

**Comment by Aris-t2** [comment]
Those are created by me:
addonmanager.png
appbutton.png
appbutton2.png
appbutton3.png
appbutton-dark.png
appbutton-grey.png
appbutton-inv.png
appmenu_ctr.png
appmenu_restart.png
appmenupane_left_sep.png
appmenupane_right_sep.png
atab.png
atab_act.png
atab_hov.png
atab_hov_tc.png
atab_tc.png
autocomplete.png
bookmarks_sidebar.png
ctrrestart.png
ctrrestart@2x.png
fx_mockup.png
nt_aero*.png
nt_win8*.png
ntab*.png
oldsearch.png
palette_ctr.png
prefs_window.png
reader.png
space1.png
space2.png
tab_empty.png

All other files are either directly from (older) Firefox versions or based on files from Firefox.

None of the files had a svg source.

**Comment by spwhitton** [comment]
Thanks, that's great.
