### ISSUE TITLE
"Tabs on Top" not working with "Hide Tabs Toolbar with only one visible tab" enabled since FX48

### ISSUE THREAD

**Issue by sven-cnrd** [Aris-t2/ClassicThemeRestorer#248]
Since I upgraded to FX48, I always get an empty additional bar avobe the Tab Toolbar. I have both of the following options enabled:

"Tabs on Top"
"Hide Tabs Toolbar with only one visible tab"

Hiding the Tab Toolbar with only one visible Tab still works. But regardless of the amount of open tabs, the additional empty bar stays above the tab toolbar.
If I disable the option "Hide Tabs Toolbar with only one visible tab", the empty bar is gone - but instead the tab bar stays visible with only one tab, of course.

Attached are four pictures for reference. 

![fx47 - one tab](https://cloud.githubusercontent.com/assets/20811375/17359198/dd814866-5965-11e6-8dc9-199c90b6bf67.png)
![fx48 - one tab](https://cloud.githubusercontent.com/assets/20811375/17359199/dd82201a-5965-11e6-9cbe-0afabacade6f.png)
![fx48 - two tabs](https://cloud.githubusercontent.com/assets/20811375/17359201/dd8af258-5965-11e6-96c1-d20201bae34c.png)
![fx47 - two tabs](https://cloud.githubusercontent.com/assets/20811375/17359200/dd894eda-5965-11e6-9ee3-7a1b06bcea8c.png)

**Comment by sven-cnrd** [comment]
Forgot to mention: If I disable the Option "Hide Tabs Toolbar with only one visible tab", restart, and enable it again it works.  If I restart again it's broken again. 
Additionally, If I have multiple tabs open and resize the windows to anything but fullscreen, the additional emtpy bar goes away and does not come back when switching back to fullscreen.

**Comment by Aris-t2** [comment]
There is an ongoing discussion on CTR support forum about issues with "Hide Tabs Toolbar with only one visible tab" option.

Try to install the latest CTR beta on a new browser profile. Use Portable Firefox to not mess around with your current setup while testing. Make also sure you are testing with Windows 10s default theme (just to be sure).

**Comment by sven-cnrd** [comment]
Unfortunately I don't have access to a Win 10 System, so I am testing on Win8x64 instead.
I just set up a Firefox 48 Portable x86 and installed the latest CTR Version 1.5.5.2beta1. No further customization, just imported my usual settings via JSON (attached). Same Problem.

[CTRpreferences.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/399391/CTRpreferences.zip)

Since Firefox 47 (maybe even 46, I don't recall it exactly) I had the same problem about once every few hours, but I was never able to reproduce it. I just ignored it, because opening a new window fixed it temporarily. But since Fx48 its a permanent problem.

**Comment by Aris-t2** [comment]
Enable the option Tabs (1) > Hide Tabs Toolbar with only one visible tab > Keep titlebar

I assumed you are using Win10, because Win8s theme looks similar, but that is not really important for that case anyway.

**Comment by sven-cnrd** [comment]
No, activating this checkbox does not solve the problem, it only changes it in a weird way. It's hard to describe this in words, because something is really wrong with this options in at least Fx 47 and 48. I invested some time yesterday evening and also tested with Fx45 portable compared to Fx48 portable, both with the latest CTR beta 3 and the same JSON import. Today I recorded the different behaviour:
(x264 AVI containers in the ZIPs)

[Fx45.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/401025/Fx45.zip):
Please note that it never shows an additional empty bar above the tab bar / navigation bar, no matter how many tabs are open and if the windows is maximized or not. The Windows-Controls in the top right corner are always on the firefox bars and never on their own bar.

[Fx48.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/401026/Fx48.zip):
Please note how the Windows-controls are rendered in an otherwise empty bar above the Tab/Navigation bar several times:
- right after the start wit one tab and after opening other tabs
- the problem gets fixed after resizing the window at second 8 and stays fixed until resizing it again at second 13.
- when maximizing the window again at second 18 it gets fixed again
- and finally it's broken again after the resizing at second 28.

If you want to test yourself, these are the settings used (zipped JSON):
[CTR_test.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/401035/CTR_test.zip)

Oh, and by the way: I think the renaming of the checkbox in the latest Beta 3 was unneccesary. Because in Firefox 45, it did exactly what the old name was saying: It kept the blank bar above the navigation bar, if the tab bar is hidden because there is only one tab (as I do NOT want it, I want it hidden in all cases). In Firefox 47 and 48 it's hard to tell because somehow the hiding of the additional Window-control-bar is broken in many cases, as seen in the second video.

I hope I could make clear what the problem is, please compare with Fx45 and Fx48 and you will see it yourself.

**Comment by Aris-t2** [comment]
I see what the "problem" is.

Since Fx47 default titlebars behavior changed, meaning results the preferences CTR offers for "hide tabs toolbar with one visible tab" and its sub option(s) changed. I tried to rewrite big parts of them, but the result was different from what CTR does on Firefox 45/46 (that code left unchanged).

Before Fx47:
If "Keep titlebar (now 'adjust titlebar space')" was active, code to ensure visibility of the actual titlebar was applied. If it was disabled, no code was applied for that matter.

Fx47:
In Firefox 47 everything changed and offered different results. Now CTR needs to apply code to reduce the gap even, if "Keep titlebar (now 'adjust titlebar space')" is disabled.

All this leads to two different results we see in your videos.

I tweaked some things here and there to improve tabs toolbar and titlebar appearance an most cases, but there are still some where things do not work like before. Run some tests with the newest beta: https://addons.mozilla.org/addon/classicthemerestorer/versions/1.5.5.2beta4

**Comment by sven-cnrd** [comment]
Woah, you are fast. Problem fixed. Everything works as it used to be in Fx45. One Tab, Two Tabs, maximized or not - no difference anymore. I think it's time to get this said: Thank you for turning Firefox into the most awesome browser again, and of course thank you for the great support.

Attached are two pictures of what it looks like now (with the window maximized):
![onetab](https://cloud.githubusercontent.com/assets/20811375/17397981/cd3f0152-5a3a-11e6-87d1-40676088cd87.PNG)
![multipletabs](https://cloud.githubusercontent.com/assets/20811375/17397982/cd43d646-5a3a-11e6-9531-0b924fe5cbc5.PNG)

Yes, the top of the pictures is really the top of the screen. I know, I just got what I asked for, you removed the unnecessary space above the address bar / tabs. :-)
But I think it would be wise to leave at least one pixel of space above it, if possible. Anyway, great job so far, thank you again.

**Comment by Aris-t2** [comment]
I will look into it.

**Comment by Aris-t2** [comment]
Fixed on latest beta/release build.
