### ISSUE TITLE
URL bar not working in Nightly.

### ISSUE THREAD

**Issue by streetwolf** [Aris-t2/ClassicThemeRestorer#249]
Some patch prevents going to sites via the url bar. Nothing happens. The regression range is:

Good:
https://hg.mozilla.org/integration/mozi ... 88c32698ec

Bad:
https://hg.mozilla.org/integration/mozi ... 8aa5ce902e

The problem is caused by enabling Location Bar (3) Autocomplete popup|Alternate appearance. When I uncheck the option things work fine.

**Comment by Aris-t2** [comment]
I already uploaded a fixed beta. If nothing changes, it will go to release channel on Friday.

https://addons.mozilla.org/addon/classicthemerestorer/versions/1.5.5.2beta5

**Comment by streetwolf** [comment]
Works fine now.  thanks Aris.
