### ISSUE TITLE
Location bar autocomplete popup shown empty in secondary display (Mac OS X Yosemite)

### ISSUE THREAD

**Issue by atelierJVA** [Aris-t2/ClassicThemeRestorer#259]
**Description**:
In a two-display setup if:

- the `Location bar:Disable height limit` setting is checked and,
- the secondary display (the one without the menu bar in the System `Preferences:Displays:Arrangement` in on bottom 
![displays_arrangement](https://cloud.githubusercontent.com/assets/6129552/17608808/7d1cae0c-6072-11e6-8432-8017a22c3129.png)

if I start typing in the location bar in a Firefox window in the secondary display it shows just an empty rectangle

![CRT location bar issue](https://cloud.githubusercontent.com/assets/6129552/17608779/2d1fa184-6072-11e6-8267-566b6d9e6621.png)

In all other possible display arrangements it works fine.

**Configuration**:

- Firefox 48 and Firefox Developer Edition 50.0a2 (both updated to the most recent release as of 12-08-2016)
- Clean profile with only CTR 1.5.5.3beta4 installed
- Mac OS X 10.10.5

**Steps to reproduce:**
- Arrange monitors in the described way
- Check `Location bar:Disable height limit`
- Create a new Firefox window and move it to the secondary display if necessary
- Start typing in the location bar

Let me know if you need more information or want me to test anything else.

**Comment by Aris-t2** [comment]
I do not have a multi-display environment for a Mac and can not test things like that, sorry.

The "disable height limit" feature calculates the visible screen area using methods like this:

urlbbotpos = document.getElementById("urlbar").boxObject.screenY + document.getElementById("urlbar").boxObject.height;
popupheight= screen.availHeight - urlbbotpos - 3;

Most likely the available height gets miscalculated somehow and causes this issue.

**Comment by Aris-t2** [comment]
The "disable height limit" calculates the value depending on the screen height. You could try the new option in today's update, that allows you to set a manual height limit for autocomplete popup.

Not sure, if this changes anything for your setup or not, but it still would be good to know, if it does.

Try height values of 500, 600, .... 2000 to see, if a lower value than the screen height works and which value is the first causing this issue.

**Comment by atelierJVA** [comment]
I think I found the cause and a solution.
			
**Cause:**
			
The property `document.getElementById("urlbar").boxObject.y` is based on the total height of the system desktop, that is, for a vertical setup like mine, the sum of the height of both displays; so when the program calculates the height for a window in the bottom (and shorter) display it gets a negative value.
			
For example, these are the values I get in my system:
			
 | Display 1 | Display 2
------| -------- | --------
Display height | 1200 | 900	
`screen.availableHeight` | 1173 | 877
`document.getElementById("urlbar").boxObject.y` | 49 | 1249
Calculated `height` | 1100 | -396 &#9888;


			
**Solution:**
			
Offset `urlbbotpos` by the value the display height that you can obtain from `window.screen.top`:
		
```
// urlbars bottom **relative** position
var urlbbotpos = document.getElementById("urlbar").boxObject.screenY + document.getElementById("urlbar").boxObject.height - window.screen.top;
```
			
I have tested it in my Mac and in a single display Windows PC, and works fine in both.

Thank you very much for your help with this issue.

**Comment by Aris-t2** [comment]
Thanks for finding the solution, great job. I will add it to CTR 1.5.6beta1+.
