### ISSUE TITLE
[Feature request] Location bar (3) > Highlighting of text hits > remove bold state on recent Firefox builds

### ISSUE THREAD

**Issue by withero** [Aris-t2/ClassicThemeRestorer#261]
如题， 地址栏输入时不想启用任何高亮提醒，但加粗不能取消。

**Edit by CTR dev.:**
Google translate:
"As stated, the address bar when you do not want to start any highlighted reminders, bold but not canceled."

**Comment by Aris-t2** [comment]
Please write only in English here!

Google translate:
"Address bar (3) is highlighted in bold text when the configuration can not be canceled"

"As stated, the address bar when you do not want to start any highlighted reminders, bold but not canceled."

CTR only adds the "bold" highlighting, if it is not present. Recent Firefox builds offer it by default, but it is different from what CTR offers.

**Comment by Aris-t2** [comment]
Check the latest CTR beta:

![1](https://cloud.githubusercontent.com/assets/6013569/17893185/08671792-6945-11e6-8bb6-bf6c466dc4f5.png)

**Comment by withero** [comment]
It's working well. Thanks for your work.
