### ISSUE TITLE
Element properties

### ISSUE THREAD

**Issue by Zefling** [Aris-t2/ClassicThemeRestorer#265]
Hi,

Is it possible to reimplement the “properties” on context-menu ? The extension ”Element Properties“ does not work on Firefox 48 and more. For me, it's a feature of the “Classic Theme” of Firefox.

Best regards.

**Comment by Aris-t2** [comment]
Hi Zefling,

the add-on Element Properties version 9.1 works fine for me up to Firefox 51.

https://addons.mozilla.org/addon/element-properties/versions/9.1-signed

**Comment by Zefling** [comment]
Oh, it's true. 
Do you want I close this issue, or is it possible to include it?

**Comment by Aris-t2** [comment]
I would prefer to close this issue. ;-)
