### ISSUE TITLE
Add a way to choose ext language

### ISSUE THREAD

**Issue by sledgehammer999** [Aris-t2/ClassicThemeRestorer#273]
It is really frustrating to understand most entries in my native language because of the technical terms used that don't translate well from English.
Plus, it is far easier to google solutions using the english version of the ext settings.

**Comment by Aris-t2** [comment]
I'm sorry, but this is not possible. Language selection is not something a add-on can do for itself. This is handled by Firefox.
You can change the value of "general.useragent.locale" to "en-US" in about:config, so your browser thinks you are using an English locale. This way all add-ons will show their content in English localization.

**Comment by sledgehammer999** [comment]
Does the browser load **your** locale resources without being told anything from your part?
If yes, then feel free to close this.

**Comment by Aris-t2** [comment]
Yes, the browser loads your locale (set in general.useragent.locale preference) automatically (if available). If you are using a localized non-Englich Firefox version, the only way to see the English translation for add-ons is modifying that preference before opening the add-on.
