### ISSUE TITLE
New default addons and options pages look horrible on OS X

### ISSUE THREAD

**Issue by z0rc** [Aris-t2/ClassicThemeRestorer#284]
Running OS X 10.11 and recent CTR update 1.5.8 switched addons and options pages to alternate look by default. The problem is, it's horrible, for example addons page:
![screen shot 2016-10-17 at 13 44 02](https://cloud.githubusercontent.com/assets/787519/19434737/ee7f8278-946f-11e6-9ad0-5a2cadd7e4b6.png)
The text size is way too small, the buttons are smaller too, content is way to compressed by height... and there is no option to revert to default look.

Can you elaborate why this is forced without option to revert? Right now I'm considering removing the addon completely, as from my perspective it breaks way to much than fixes.

**Comment by Aris-t2** [comment]
Tastes are different.

You can of course revert both looks. They are optional (for ages):
CTR prefwindow > Options page > select 'Default appearance'
CTR prefwindow > Add-on manager > uncheck 'Alternative appearance'

**Comment by z0rc** [comment]
> CTR prefwindow > Add-on manager > uncheck 'Alternative appearance'
I wouldn't open the issue in the first place if this option was actually present.
![screen shot 2016-10-17 at 15 03 40](https://cloud.githubusercontent.com/assets/787519/19436807/eaf218ea-947a-11e6-839f-4373ae8d9a11.png)

**Comment by Aris-t2** [comment]
Looks like you have found a bug caused by the Developer Edition theme.
You are using the Developer Edition theme, right?

Please disable the theme and reopen CTRs preference window. You will see much more settings incl. the one to disable add-on managers alternative appearance. You can enabled the theme afterwards.

You can also set extensions.classicthemerestorer.alt_addonsm to false in about:config.

I will look into this issue.

**Comment by z0rc** [comment]
Pointed `about:config` worked for me without cycling themes. Thanks!

**Comment by Aris-t2** [comment]
Could you install the latest beta I just uploaded? https://addons.mozilla.org/en-us/firefox/addon/classicthemerestorer/versions/1.5.8.1beta1
It should offer proper settings visibility for add-on manager and options page on CTRs preferences window when using Developer Edition theme.

**Comment by z0rc** [comment]
Yes, this beta update fixed CTR options visibility with Dev Edition theme. Thanks for prompt feedback, you rock!
