### ISSUE TITLE
Issues with last beta of CTR (1.5.8.1beta2) and FFOX 49.0.1

### ISSUE THREAD

**Issue by typhoon71** [Aris-t2/ClassicThemeRestorer#285]
well, as soon I updated from previous beta of CTR I faced a bunch of issues.
I did fix everything I'm reporting going back to 1.5.8, but I suppose I'll report it anyway:

1- address bar disappears from the UI.
2- unable to customize using the "customize right click (the customize tab will be empty)
3- conflict with session manager (saves sessions with 17k tabs instead od just 140)

If you need anything else just ask me. Btw, seems the browser become snappier going back to 1.5.8 from previous beta, strange, maybe it's placebo.

**Comment by Aris-t2** [comment]
Is it possible your Firefox profile got damaged somehow?

1. There were not address bar related changes in recent beta builds.
2. Once the address bar is gone, Firefox stops working. There are some precautions to prevent that, but there are still add-ons out there, that can override that (Foxtab and Shareaholic for example).
3. CTR never played along with session managers especially with those, that save/modify the ui instead of just saving tab locations.

Please test CTR on a new browser profile.

**Comment by typhoon71** [comment]
My profile should be fine, also right now it's working; I will test with a clean profile with all addon and let you know, but later (tomorrow or in the weekend).

I can confirm point 2 (I didn't know about it); obviously I use the address bar and never hid it (on my own volition at least); in the addon page I read that someone was complaining about something related to the address bar in the first comment, so I reported the issues I found.

About session managers: I use the "Session Manager" addon from http://sessionmanager.mozdev.org/, it builds upon SessionStore so it should be rather compatible; the other addon I was thinking could be related was tabmix plus, since I updated it recently.

**Comment by Aris-t2** [comment]
OK, let me now what you find. Please test with latest 1.5.8.1 beta only, not with v1.5.8 release build.

With Session Manager 0.8.1.12 I was able to restore very old sessions from 2014 on my test profile without any issues (same applies to two year old TabMixPlus sessions).

**Comment by typhoon71** [comment]
It seems I'm late.
I noticed that a bunch of beta builds were released while I was away, and even a stable one.

I tested just the 1.5.8.1 stable build and for now I have no issues with it.
The address bar doesn't disappear and the session manager doesn't create 17k tabs session backup any more. Tested with a clean profile and my main profile.

Switching back to 1.5.8.1beta2 makes it go mad again.

I'd say the "something" that was causing me issues between 1.5.8.1beta2 and stable 1.5.8.1 is now  fixed one way or another. I have no other recent addon update.

I'm closing the issue.

**Comment by Aris-t2** [comment]
A change in 1.5.8.1 beta 1 handled the developer menuitems popup differently compared to 1.5.8 release. After your report, I changed the timings that popup gets addressed and added more issues catchers in 1.5.8.1 beta 3.

Anyway, good to hear the issue is fixed.

**Comment by typhoon71** [comment]
Btw, after loading an old 17k tab session with 1.5.8.1 I noticed thet the 17k tabs were all "about" tabs that got added in after the usual ~150 tabs I use (by the beta). Makes sense now, those "about" must have been popup related.
