### ISSUE TITLE
location bar (3) > alternative appearance breaks url fixup shortcuts

### ISSUE THREAD

**Issue by siavash119** [Aris-t2/ClassicThemeRestorer#286]
with the option checked. ctrl+enter, shift+enter, etc. don't work for prefixing www. and suffixing .com .net etc. 

broke a few days ago; using latest beta and latest nightly

**Comment by Aris-t2** [comment]
Default Firefox code for autocomplete popup got updated by Mozilla. I have to pass the changes to CTRs corresponding option. Next beta will fix this issue.

Note:
I could only reproduce this issue on Firefox Developer Edition and Nightly, but not on Firefox beta version.

**Comment by siavash119** [comment]
sorry for the poor explanation before: using the latest beta of CTR and latest nightly of Firefox.

thanks so much

**Comment by Aris-t2** [comment]
Test the new beta: https://addons.mozilla.org/addon/classicthemerestorer/versions/

**Comment by siavash119** [comment]
works great; thanks so much. closing
