### ISSUE TITLE
Adjustment needed in userstyles pane

### ISSUE THREAD

**Issue by MacgyverJohnson** [Aris-t2/ClassicThemeRestorer#287]
Hi there @Aris-t2 
here's how userscript(greasemonkey) pane looks like with compact view plus
![screenshot 267](https://cloud.githubusercontent.com/assets/17729946/19835794/576f2ee2-9eba-11e6-9334-1f251b68c026.png)
Heres how userstyles pane look like
![screenshot 264](https://cloud.githubusercontent.com/assets/17729946/19835799/681dbe70-9eba-11e6-8353-47856b4c50a7.png)
Previously u shared the css for compact view plus could u do that again so I could manually fix this
or if u have the time u could fix this?(move the buttons to the rightmost side of the screen
Thanks in advance!!!

**Comment by Aris-t2** [comment]
Maybe one of your add-ons or user styles/scripts is causing this. Looks like this for me on all OSs (blue only on Aero blue themes):

![1](https://cloud.githubusercontent.com/assets/6013569/19838651/6ccd952a-9ed4-11e6-9472-df0ff64fd9f2.png)

**Comment by MacgyverJohnson** [comment]
Yeah this was due to a userstyle that affected addons pag
thanks for the css
