### ISSUE TITLE
Alternative Appearance for Add-On Manager doesn't work?

### ISSUE THREAD

**Issue by Nicholas-Steel** [Aris-t2/ClassicThemeRestorer#302]
Firefox 51 beta 8 and now also beta 9 x64 (64bit), Windows 10 Pro AU x64. I can not get the left pane to be dark like it is by default in the latest stable x86 (32bit) version of Firefox.

**Comment by Aris-t2** [comment]
Works fine for me. Do you have any themes installed or other add-ons that can modify add-on managers ui?

![1](https://cloud.githubusercontent.com/assets/6013569/21386221/1ce6d3ac-c772-11e6-95e0-a62be2bbf35b.png)

![2](https://cloud.githubusercontent.com/assets/6013569/21386229/226f02d6-c772-11e6-8f67-982e9fda75ff.png)

**Comment by Nicholas-Steel** [comment]
Looks like it might be an intermittent issue, restarting Firefox seems to have resolved it.

**Comment by Aris-t2** [comment]
I might have an idea what could interfere with enabling/disabling "alt appearance" options in some cases;
the option "Toolbars > Page 3 > Blue Aero colors".
Have you tried to disable it or to disable and enable it after unsetting "alternative appearance for add-on manager".

**Comment by Nicholas-Steel** [comment]
OH, Maybe I got the Options interface confused with the Add-ons interface.

**Comment by Aris-t2** [comment]
So is enabling/disabling alternative ui for add-ons manager and options page working for you or not?

**Comment by Nicholas-Steel** [comment]
It is working, so I'll close this for now.
