### ISSUE TITLE
Opening CTR options via Add-On manager prevents you from interacting with main Firefox window

### ISSUE THREAD

**Issue by Nicholas-Steel** [Aris-t2/ClassicThemeRestorer#303]
Opening CTR options via Add-On manager prevents you from interacting with the main Firefox window (bug). Opening CTR options via the Tools menu will still allow you to interact with the main Firefox window while the CTR options interface is open.

Windows 10 x64

**Comment by Aris-t2** [comment]
Sorry, that is no bug. Firefox handles add-ons this way.

**Comment by Nicholas-Steel** [comment]
Okay no worries, I figured as much.
