### ISSUE TITLE
Copyright status of throbber-loading-ubuntu.png

### ISSUE THREAD

**Issue by spwhitton** [Aris-t2/ClassicThemeRestorer#305]
Thank you for the new 1.6.0 release of Classic Theme Restorer!

Could you provide me with the copyright status of throbber-loading-ubuntu.png, please?  Did you make the file yourself, or obtain it from another source?  If so, where?

**Comment by Aris-t2** [comment]
Extracted from Firefox 45 for Linux files.

**Comment by spwhitton** [comment]
Thank you for your prompt reply!

Could you clarify whether you mean `firefox-45.0.tar.bz2` as downloaded from `ftp.mozilla.com`, or Ubuntu's packaging of Firefox?  Since the file is from Ubuntu, I guess that Canonical hold copyright on it?

**Comment by Aris-t2** [comment]
http://ftp.mozilla.org/pub/firefox/candidates/45.5.0esr-candidates/build1/linux-i686/en-US/firefox-45.5.0esr.tar.bz2
