### ISSUE TITLE
Huge memory and cpu usage since 1.6.0(.1)

### ISSUE THREAD

**Issue by guniu** [Aris-t2/ClassicThemeRestorer#306]
Last 2 days my firefox started to leak memory. When nearing 1.1GB (after few hours) it was slower and slower on rendering already opened tabs (full CPU usage) and eventually it would crash. I searched the cause and I found that CTR updated on Dec 22nd, which is when I started noticing the issue.

Now I'm a whole day with CTR disabled and everything works without a problem, no memory leaks, no high CPU usage. So I'm pretty sure something went wrong with the latest update of CTR.

My other add-ons: http://i.imgur.com/ls9ho5m.png
FF 50.1.0

**Comment by Aris-t2** [comment]
Hi,

I'm sure, nothing in CTR increases memory usage on purpose. Some features however may have an greater impact than others. To name them:
- custom tab width
- activity indicator
- favicon in location bar
Please make sure these settings are disabled and test again. Alternatively you can reset CTR settings to default and retest.

I did not notice such issues on any test system (or my main systems) and no other user reported anything similar.

**Comment by guniu** [comment]
Ok, false alarm, got a memory leak today with CTR disabled, even thought yesterday it ran whole day without a problem. Maybe it's tweetdeck, cause I opened it today. Need more testing, and sorry for the fuss.
