### ISSUE TITLE
Ugly bar across entire screen

### ISSUE THREAD

**Issue by Krawk** [Aris-t2/ClassicThemeRestorer#307]
I just went from FF 43 to FF 45 and downloaded newest Classic Theme Restorer and see a new issue I can't figure out how to get rid of. Immediately above the Tabs I have a Bookmarks button, but the entire horizontal length of the screen has a semi-transparent bar. As I use a custom graphic on the screen, it makes it rather ugly. Removing the Bookmarks button leaves the bar on the screen.  See my half size screen capture. If there were a manual of some sort I might be able to figure it out (??)
Apparently trying to drag this bar simply causes FF to reduce the screen size.
![gray bar](https://cloud.githubusercontent.com/assets/13263340/21472596/0f8bbb32-cab0-11e6-887f-224409078084.jpg)

TIA

**Comment by Aris-t2** [comment]
Which OS are you using?
The toolbar you have the bookmarks button on, which toolbar is this, CTRs additional toolbar, bookmarks toolbar or a third party toolbar?

**Comment by Krawk** [comment]
I am running a vanilla browser. The graphics on the top is simply a theme. I can make the "Bookmarks" button go away and the stripe is still there.

**Comment by Aris-t2** [comment]
Have you checked/unchecked the options I mentioned?

**Comment by Aris-t2** [comment]
Fiexed on 1.6.1 release/beta.
