### ISSUE TITLE
[Feature request] Add ability to organize search engines into folders.

### ISSUE THREAD

**Issue by c8c8** [Aris-t2/ClassicThemeRestorer#308]
I use a lot of search engines.  It would sure be helpful if CRT's classic search bar worked like the old search bar where I could add folders and sort my engines into them.  Thank you for any consideration :)

**Comment by Aris-t2** [comment]
I'm sorry, CTR won't get such a feature, but there is an add-on, that should work fine:
https://github.com/Baton34/organize-search-engines/releases
