### ISSUE TITLE
Inactive tabs color went black after updating to nightly 53.0a1 (2017-01-06)

### ISSUE THREAD

**Issue by gelirhil** [Aris-t2/ClassicThemeRestorer#309]
After updating to nightly 53.0a1 (2017-01-06) (win64) inactive tabs color suddenly went black as shown in attached screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/24973373/21740979/c8c014b6-d4da-11e6-8b11-31aa8e62411d.PNG)
Active tab still looks normal. Yet inactive tabs color can be changed by enabling CTR tabs colors settings. The issue occurs only if all CTR color settings are disabled (which is by default).
Downgrading to nightly 53.0a1 (2017-01-05) fixes the problem completely.

**Comment by Aris-t2** [comment]
Install newest CTR beta (1.6.1b3): https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by gelirhil** [comment]
Thank you, problem solved.
