### ISSUE TITLE
The "Did you mean to visit" is not gone...

### ISSUE THREAD

**Issue by Tsukiyomaru0** [Aris-t2/ClassicThemeRestorer#312]
![untitled-2](https://cloud.githubusercontent.com/assets/24899370/21959540/e3aa1208-daa8-11e6-99d3-7987e86b4b19.png)

See? It is showing up. It might be my ISP doing DNS ransom as usual, I'll nag to them eventually anyways.

**Comment by Aris-t2** [comment]
How is this Google site feaute CTR related?

**Comment by Tsukiyomaru0** [comment]
I don't think it is Google site related... If I leave google, that stupid thing follows me until I go to a third or fourth page or close it manually. It might be Firefox's Chromium doing its thing again, but could be my ISP's shenanigans. Still odd, I've never changed ISP and suddenly this starts happening again. It's the same only for single words without a search prefix ( "?" ).

**Comment by Aris-t2** [comment]
Well, there is nothing in CTR that can create, move or remove that line. I never saw it before. Might be a Firefox feature or an add-on feature, but I really can't tell.
I suggest to report this on Mozillazines support area, where many users have a superb knowhow about almost everything Firefox can or can not: http://forums.mozillazine.org/viewforum.php?f=38

I bet you issue can get solved faster there than on CTRs support area.

Just to be sure, it has nothing to do with add-ons or your profile:
- download and setup Portable Firefox: http://portableapps.com/apps/internet/firefox_portable
- close your current/default Firefox
- run Portable Firefox
- install only CTR 
- run tests

**Comment by RobertZenz** [comment]
This could be the so called "notification bar" of Firefox, accessible with the CSS rule `.notificationbox-stack`. As far as I'm aware the same bar is used for the plugin question and other stuff.

**Comment by Aris-t2** [comment]
You might be right.

I still don't see what this has to do with CTR.

**Comment by Tsukiyomaru0** [comment]
Well, Aris....
![image](https://cloud.githubusercontent.com/assets/24899370/21992650/16152554-dbf6-11e6-8d2a-6c7efa4739f7.png)

**Comment by Aris-t2** [comment]
That option removes those items from "Autocomplete popup". Haven't you noticed the category and options names? Why would it do anything else?

"**Location bar** > _Autocomplete popup_ > Remove ...."

**Comment by Tsukiyomaru0** [comment]
Oh, is it... Then it comes out odd... Why is this appearing NOW then?

**Comment by Aris-t2** [comment]
No idea. Does not occur for me on any browser version or system I run tests on.

Read what I have written two days ago (->Mozillazine, ->Portable Firefox). Maybe that will solve your issue.

Anyway Google is your friend:
https://support.mozilla.org/de/questions/1129065
https://support.mozilla.org/de/questions/1026085
http://askubuntu.com/questions/577492/how-to-make-firefox-stop-suggesting-if-i-meant-to-go-a-website-when-i-search
https://www.wilderssecurity.com/threads/firefoxs-annoying-would-you-like-to-go-to.384136/
http://forums.mozillazine.org/viewtopic.php?f=38&t=2943803&p=14215841

**Comment by Tsukiyomaru0** [comment]
Seen all of those... None works... And the download of portable firefox breaks halfway.

**Comment by RobertZenz** [comment]
@Tsukiyomaru0 Hey, could you get [ThinBars](https://addons.mozilla.org/en-US/firefox/addon/thin-bars/) and see if that makes it vanish? ThinBars does have an option to hide the notification bar.

**Comment by Tsukiyomaru0** [comment]
nevermind, found the cause... Bad cookies, probably pertaining to Google.
