### ISSUE TITLE
[Fx55+] switch for 'privacy.resistFingerprinting' preference

### ISSUE THREAD

**Issue by KOLANICH** [Aris-t2/ClassicThemeRestorer#318]
Add a tick into a "advanced".

**Comment by Aris-t2** [comment]
This preference is not present in Firefox by default. What exactly does it trigger?

**Comment by KOLANICH** [comment]
something from https://bugzilla.mozilla.org/show_bug.cgi?id=1329996 I guess
https://dxr.mozilla.org/mozilla-central/search?q=privacy.resistFingerprinting&redirect=false

**Comment by Aris-t2** [comment]
Sounds like this security feature will be worth adding a switch for once it is officially part of Firefox, but only if Firefox does not get an own switch for it. According to the above Bugzilla page the main target is Firefox 54. Although todays Fx 54 Nightly is already out, that preference was not yet added.

**Comment by Atavic** [comment]
The [Tor Uplift Project](https://wiki.mozilla.org/Security/Tor_Uplift/Tracking) has many preferences, all listed here: https://github.com/ghacksuserjs/ghacks-user.js/issues/7

**Comment by Aris-t2** [comment]
This preference is now part of Firefox 55 and will be added to CTR 1.6.5.

**Comment by Aris-t2** [comment]
Get 1.6.5 release from here: https://addons.mozilla.org//addon/classicthemerestorer/versions/1.6.5
