### ISSUE TITLE
Unremovable border in tabsontop_offextra.css

### ISSUE THREAD

**Issue by jabcreations** [Aris-t2/ClassicThemeRestorer#319]
In the file **tabsontop_offextra.css** the border can not be removed and I've spent a very good chunk of time and an overzealous use of **!important** without any success. The only way to get rid of the border is if I give the entire top deck element a height and overflow though that obviously wouldn't work well if you change the number of toolbars.

This was introduced in a quiet 1.61 update (it doesn't appear in Firefox 45 ESR but it does in 1.61 using Firefox 54 Nightly.

The offending border can be found here:

	@media all and (-moz-windows-theme:aero) {
		#main-window[defaultfxtheme="true"] #TabsToolbar:not(:-moz-lwtheme) {
		  background: #dbeaf9 !important;
		}
	    #main-window[defaultfxtheme="true"][tabsontop="false"] #TabsToolbar:not(:-moz-lwtheme) {
		  border-bottom: 1px solid hsla(209,67%,12%,0.25) !important; /*#aabccf*/
	    }
	}

**Comment by Aris-t2** [comment]
That file was modified in 1.6.1, but the line you are mentioned was added a long time ago.

To remove it use this code in Stylish or on prefwindows "custom css area":

```css
/*AGENT_SHEET*/
#main-window[defaultfxtheme="true"][tabsontop="false"] #navigator-toolbox #TabsToolbar:not(:-moz-lwtheme) {
 border-bottom: 0px !important;
}
```

**Comment by jabcreations** [comment]
That doesn't though and I've tried a few iterations. This doesn't occur in Firefox 45 ESR with 1.6.1 but it does with Firefox 54 Nightly and 1.6.1.

Windows 7 Pro 64 Bit, Aero with transparency disabled. In Appearance for addons there are no enabled themes.

Here is a screen shot and below that is just the code from **userChrome.css** for just that profile which is specific to that version of Firefox.

![github](https://cloud.githubusercontent.com/assets/5625045/22400365/8fc558ea-e580-11e6-8828-52b5af65ea61.png)



/** Toolbar Items **/
toolbarspacer {min-width: 32px;}

/* Search Menu, drop-down button. */
.searchbar-engine-button
{
 height: 20px;
 width: 30px;
}

/* Search Submit Button */
.search-go-container *
{
 float: right;
 height: 20px;
 min-width: 24px;
}

/* Search Menu, drop-down button margin fix. */
.searchbar-textbox > hbox > hbox
{
 margin-left: 0 !important;
}

/*** Address Bar ***/
#identity-box {margin-left: 2px;}
#identity-box hbox {display: none !important;}
#urlbar {font-size: 17px !important; margin: 0 0 0 -7px !important;}

/* Tab toolbar reduced margin-top waste*/
.tabbrowser-tab {margin-top: 1px !important;}

/* Toolbar buttons icons-with-text-on-side fix. */
.toolbarbutton-1 {-moz-box-orient: horizontal !important; max-height: 24px;}
.toolbarbutton-1 > .toolbarbutton-menubutton-button {-moz-box-orient: horizontal !important;}/*new bookmarks toolbar item*/

/*** Adblock Plus extension button fix ***/
#abp-toolbarbutton {width: 120px;}
#abp-toolbarbutton > hbox > vbox {-moz-box-orient: horizontal !important;}

/*** Go Button ***/
#urlbar-reload-button, #urlbar-stop-button, #urlbar-icons > #star-button {display: none !important;}
#urlbar-go-button {height: 18px; max-width: 42px !important; overflow: hidden;}
#urlbar-go-button label {display: block !important;}
#urlbar-go-button image {margin-right: 4px;}
#urlbar-go-button label {height: 20px !important; line-height: 15px;}
#urlbar-go-button label.toolbarbutton-text::before {color: #fff; content: 'Go'; padding: 0 2px 0 2px; position: relative; top: -2px !important;}
#forward-button {display: none; padding: 0 !important;}
#urlbar-go-button {margin: 0 !important;}
/*** /Go Button ***/



/**************************************************/


/*** Address Bar Fixes ***/
#urlbar {height: 23px !important;}
#urlbar hbox, #urlbar vbox, .urlbar-progress-layer {height: 20px !important; max-height: 20px !important; overflow: hidden !important;}/* Address Bar 20px without effecting context-menu. */

#alltabs-button {min-width: 80px !important;}



















/*** <Firefox 54> ***/

/*** <works> ***/

/*** General Toolbar background-color ***/
#navigator-toolbox, #alltabs-button {background-color: #000 !important;}

/*** Blank page before a page loads. ***/
.tabbrowser-tabbox {background-color: #000; color: #fff;}

/*** File Menu Text Color ***/
#menubar-items * {color: #fff !important;}

/*** Fixes File Menu drop-down Thick Border ***/
popup:not(#autoscroller), menupopup, popup menu, menupopup menu {-moz-appearance: none !important; border: #444 solid 1px !important;}


/*** File Menu color fixes, focus not working though! (keyboard arrows versus mouse:hover ***/
menuitem, .splitmenu-menuitem {-moz-appearance: none !important;}
#menubar-items menu:active,
#menubar-items menu:focus,
#menubar-items menu:hover,
#menubar-items menuitem:active,
#menubar-items menuitem:focus,
#menubar-items menuitem:hover,
#menubar-items menuitem:active *,
#menubar-items menuitem:focus *,
#menubar-items menuitem:hover * {background-color: #777 !important; background-image: none !important;}



/*** Toolbar Buttons Color ***/
.toolbarbutton-text {color: #fff;}

/*** Address Bar margin fix, super-fuck retarded ***/
#PersonalToolbar {height: 24px; margin-left: -13px !important; overflow: hidden;}

/*** Tabs ***/
#TabsToolbar, #TabsToolbar * {background-color: #000; color: #fff;}

/* Address and Search Bar */
#urlbar-container *, #search-container * {background-color: #222 !important; color: #fff !important; margin: 0 !important;}

/*** Address Bar vertical-text alignment fix ***/
#urlbar > * {margin-top: 1px !important;}

/* Individual Tab Margins*/
#TabsToolbar tab.tabbrowser-tab {margin-right: 1px !important;}
/*** </works> ***/


/*** <testing> ***/




#urlbar {height: 25px !impotant;}
#navigator-toolbox > toolbar:not(#toolbar-menubar):not(#TabsToolbar):not(:-moz-lwtheme),
 #browser-bottombox:not(:-moz-lwtheme),
 .browserContainer > findbar
{
background-color: #000 !important;
}





#TabsToolbar,
#TabsToolbar *,
.tab-background-start[selected=true]::after,
.tab-background-start[selected=true]::before,
.tab-background-start,
.tab-background-end,
.tab-background-end[selected=true]::after,
.tab-background-end[selected=true]::before,
.tabbrowser-tab .tab-stack .tab-background,
.tabs-newtab-button,
#tabbrowser-tabs,
.tabbrowser-tab,
.tabbrowser-tab[pinned],
.tabbrowser-tab .tab-stack,
.tabbrowser-tab .tab-stack > .tab-content,

#TabsToolbar .tabs-newtab-button,	#TabsToolbar .tabbrowser-tab
{
 border: 0 !important;
 margin: 0 !important;
}
/*
 height: 24px !important;
 
 max-height: 24px !important;
 min-height: 24px !important;
*/





#titlebar, #titlebar * {background-color: #000; color: #fff;}
#titlebartab-view-deck, #titlebartab-view-deck * {background-color: #000; color: #fff; backface-visibility: hidden;}

/*
works but bleeds outside of border...so need to fix border first >__>
#TabsToolbar .tabbrowser-tab[selected="true"] > * * {background-color: #f0f !important;}
*/


#TabsToolbar .tabbrowser-tab {border: #444 solid 1px !important; border-radius: 2px !important;}
#TabsToolbar .tabbrowser-tab[selected="true"] {border: #aaa solid 1px !important; border-radius: 2px !important;}




#TabsToolbar tab .tab-text {line-height: 22px !important; margin-left: 8px !important;}
#TabsToolbar tab, #TabsToolbar tab *:not(.tab-icon-image) {height: 24px !important; max-height: 24px !important; min-height: 24px !important;}

#TabsToolbar .tabbrowser-tab[selected="true"], #TabsToolbar .tabbrowser-tab[selected="true"] *
{/*at least makes selected tab's text bold! */
  font-size: 17px;
  font-weight: bold !important;
  
  color: #fff !important;
  /*color: rgba(255,255,255,1) !important;*/
  /*background-image: linear-gradient(rgba(102,51,102,.85), rgba(102,51,102,.85) 50%),
                    linear-gradient(-moz-dialog, -moz-dialog) !important;*/
}


/*** </testing> ***/
/*** </Firefox 54> ***/




#TabsToolbar {height: 24px; overflow: hidden;}



/*#menubar-items * {background-color: #0f0 !important;}*/


/* Remove # selector and will work cross-browser for the most part! */
#menubar-items menupopup * {background-color: #000 !important; border-width: 0 !important; outline: none !important;}







#nav-bar {height: 24px !important; overflow: hidden !important;}
#nav-bar toolbarbutton {padding: 0 4px 0 4px !important;}

#nav-bar-customization-target > *:not(#abp-toolbarbutton) > *,
#nav-bar-customization-target > toolbaritem > *:not(#abp-toolbarbutton) > *
{height: 22px !important; border-width: 0 !important;}
/* .toolbarbutton-badge-stack, #nav-bar toolbarbutton > .toolbarbutton-badge-stack */



#menubar-items menuseparator {
/*
-moz-appearance: none !important;

list-style-image: none !important;

background: none !important;

border: none !important;
border-top: solid 1px #f0f !important;
*/
border-width: 0 !important;
height: 0 !important;
padding: 0 !important;
color: #f00 !important;
background-color: #00f !important;
}









 	@media all and (-moz-windows-theme:aero)
  {
		#main-window[defaultfxtheme="true"] #TabsToolbar:not(:-moz-lwtheme)
  {
		  background: #dbeaf9 !important;
		}
	    #main-window[defaultfxtheme="true"][tabsontop="false"] #TabsToolbar:not(:-moz-lwtheme) {
		  border-bottom: 0 solid transparent !important; /*#aabccf*/
	    }
	}
 
 
 	    #main-window[defaultfxtheme="true"][tabsontop="false"] #TabsToolbar:not(:-moz-lwtheme) {
		  border-bottom: none !important;
	    }
 
 
 
 
 /*
 #global-notificationbox {display: none !important;}
 */
 
 #global-notificationbox {height: 0 !important;}
 
 
 
 /*AGENT_SHEET*/
#main-window[defaultfxtheme="true"][tabsontop="false"] #navigator-toolbox #TabsToolbar:not(:-moz-lwtheme) {
 border-bottom: 0px !important;
}

**Comment by Aris-t2** [comment]
The code you are after it this one:

```css
/*AGENT_SHEET*/
#navigator-toolbox:after {
  border-bottom: unset !important;
}
```
