### ISSUE TITLE
[Blackfox/Lavafox complete theme] Tabs not on top not working

### ISSUE THREAD

**Issue by ghost** [Aris-t2/ClassicThemeRestorer#327]
So I suppose, reading about the new updates from Mozilla, that reporting that the Tabs Not on Top option no longer working properly is a moot point? In any case, you can only see the very tops of the tabs with a greyed out bar of space between the bookmarks and the thin tops of the tabs.

![image](https://cloud.githubusercontent.com/assets/26395521/23881074/4c34a830-082e-11e7-8cf4-b6afa3ee0bf0.png)

**Comment by Aris-t2** [comment]
Didn't the last update of Lavafox/Blackfox theme fix that issue? Anyway, next CTR beta will solve this problem too.

**Comment by Aris-t2** [comment]
Fixed on latest beta and release version of CTR.
