### ISSUE TITLE
Support for container tabs

### ISSUE THREAD

**Issue by allo-** [Aris-t2/ClassicThemeRestorer#333]
Firefox new container tabs show a coloured bar above the tab in the australis theme, which isn't visible with classic theme restorer and square tabs. CTR should try to display the coloured bar as well.

**Comment by Aris-t2** [comment]
Container tabs are not officially active on release or beta channels yet, but working once a user switches the corresponding about:config preference.

Unfortunately the way Firefox manages to display the color line above default curved tabs is incompatible to the way squared tabs are styled in CTR. For now the visual indicator in location bar helps distinguishing between tabs and container tabs.

**Comment by allo-** [comment]
The location bar indicator works for the active tab, but not for others.

What about some option, which colours other parts of the tab? There are a lot of extensions coloring tabs, i.e. by the url, by the read/unread status, by the age and much more. To keep it similiar its probably enough to use a colored bar inside the tab itself.

**Comment by Aris-t2** [comment]
First I thought adding something like you suggested, but now I found a workaround to actually add a line on top of squared container tabs. It looks not exacly the same though.

![1](https://cloud.githubusercontent.com/assets/6013569/24404746/bed4b264-13c2-11e7-9fc3-322459c526b4.png)

**Comment by allo-** [comment]
I guess i like it even better than the soft line.
Anyway, great how fast you're working on feature requests!

**Comment by Aris-t2** [comment]
Fixed on latest beta and release version of CTR.
