### ISSUE TITLE
"Replace labels with icons" in add-ons: compatibility with Stylish extension

### ISSUE THREAD

**Issue by vitaliylag** [Aris-t2/ClassicThemeRestorer#336]
Stylish scripts don't have "Settings" button they have "Edit" button, but after replacing with icons there is "Settings" icon not "Edit".

You can fix it using this css:
```css
[type="userstyle"] .addon-control {
    /*...*/
}
```

**Comment by Aris-t2** [comment]
I used the settings icon, because the default "Toolbar.png" (available in browsers default files) does not provide an edit icon.

Paste this into location bar and tell me which icon would be more convenient:
```
chrome://browser/skin/Toolbar.png
```

![toolbar](https://cloud.githubusercontent.com/assets/6013569/24795963/7fce167a-1b8b-11e7-8d3f-43266e1c1e00.png)

**Comment by vitaliylag** [comment]
Please use 2x version:
```
chrome://browser/skin/Toolbar@2x.png
```

You can find icon with needed license here https://www.iconfinder.com/

**Comment by Aris-t2** [comment]
This is just a tiny side option. The reason for using internal icons was save space by not adding own icons. I'm not going to deal with any license stuff just to add one icon for a CTR sub option, that only is visible when another third party add-on is installed.

Feel free to override CTRs code with whatever you like:

```
richlistitem[type="userstyle"] .control-container button[oncommand="document.getBindingParent(document.getBindingParent(this)).openEdit();"] image{
  list-style-image: url("chrome://browser/skin/Toolbar.png");
  -moz-image-region: rect(0, 468px, 18px, 450px);
}
```

I will take care of the Toolbar@2x.png case.

**Comment by Aris-t2** [comment]
Get 1.6.5 release from here: https://addons.mozilla.org//addon/classicthemerestorer/versions/1.6.5
