### ISSUE TITLE
[Linux][Fx53] CTR causes crashes on certain sites with 'Allow multiselect operations on tabs' add-on enabled

### ISSUE THREAD

**Issue by bongochong** [Aris-t2/ClassicThemeRestorer#340]
Sites Affected:
- thepiratebay.org (after browsing around for a few seconds)
- academia.edu (upon attempting login via google, which leads me to believe it could be causing crashes on other sites that allow one to log in with a google account)

I confirmed this via backing up my firefox profile, starting firefox on a fresh profile, installing CTR, and attempting to utilize those sites. Always crashed with CTR, and never crashed without CTR. Turning off javascript completely seems to resolve the issue, but JS is necessary on sites that allow one to log in with their google account.

This is on FF 53 under Linux (64-bit) with a relatively vanilla Ubuntu install (though I am using the HWE stack for newer kernel and xorg releases). FF is the default version included in the Ubuntu repos. No custom theme for FF. Before going the fresh profile route, I tried disabling settings in CTR that I thought could be the cause of the issue (old search, certain options under address bar and security icons) to no avail. Let me know if i can provide any more information.

P.S. This has been an issue on the last three beta versions I've tried, and the last two stable versions, but only under FF 53.

P.P.S. CTR preferences here: http://paste.ubuntu.com/24488302/

**Comment by Aris-t2** [comment]
I never experienced such an issue and never got a similar reports before. All I can say is CTR does not interfere with websites and their JavaScript code. A few tiny options change css stuff for images or browsers own HTML pages, but that is it. Did you experience this on other OSs or Linux versions too?

Can you open your browser console and monitor what happens (if anything at all) while trying to browse the websites btw. login into them? Does this also happen with **google.com** and **youtube.com**? Both use Google login for me too.

I'm running Ubuntu 17.04 (32Bit) in a VM without adding any new packages (except VBox guest additions), just a fresh install and those sites to not crash Firefox for me. I know this setup is not identical to yours, but that was as close as possible atm.

Can you run some other tests, if possible:
- test on a machine with fresh installed Ubuntu (17.04) without HWE stack
- test 32bit Firefox, if current Firefox is 64bit and vice versa
- test Firefox 54 beta
- test the Firefox preset in CTR (CTR prefs>Settings button>Firefox preset) 
- disable/enable hardware acceleration in Firefox settings
- test on a different Linux
- test older release builds of CTR to find first version this issue happens with

**Comment by bongochong** [comment]
I'll do as much of that as I can and report back ASAP. Thanks for the responsiveness!

**Comment by bongochong** [comment]
Okay, so I decided to see if this issue presented itself on my Windows installation with the same Firefox and CTR settings. It did. I then reset CTR to its defaults and the problem was resolved. I reset CTR to its defaults on Linux and the problem was resolved as well. I'm still not sure what was going on with the way I configured CTR, but if after reconfiguring it to my liking I experience the issue again, I'll let you know. BTW, I did what you suggested with hardware acceleration and no difference whether enabled or disabled. Only resetting CTR to defaults resolved the issue.

**Comment by bongochong** [comment]
OK figured it out, CTR and [this extension](https://addons.mozilla.org/en-US/firefox/addon/bug-566510/) conflict under FF 53 for some reason. Don't know how or why, but they do, and it wasn't an issue in previous releases of Firefox. That extension, a few others, and CTR are pretty essential for me, and when I was troubleshooting with a fresh profile, I'd still add the "Allow multiselect operations on tabs" extension and 5 or 6 others after installing CTR. Poor form for troubleshooting, I know.

With the aforementioned extension disabled, I can configure CTR any which way I please and the bug with crashing on those sites disappears. With that extension enabled, everything is fine as long as CTR is using the default settings. Though when I change to the classic preset, or import my old preferences, the bug with crashing on certain sites when JS is enabled reappears.

Please let me know if I should file a new issue, or modify this existing one. The conflict between these extensions happens under 64-bit installs of Ubuntu Linux 16.04 and Windows 7.

**Comment by Aris-t2** [comment]
It is a very strage way to test CTR on a "clean profile", if you additionally install 5-6 other add-ons too. ;-)
Different tab add-ons do not play well together, so I suggest to disable some of CTRs tab settings to find which one causes the conflict (just for me to know). Keep in mind "Allow multiselect operations on tabs" was not updated for 3,5 years. Outdated add-ons can not be supported correctly neither by Firefox nor by other add-ons. Catching their attempt to use not supported code areas or instructions is impossible in most cases. 

One of these CTR settings is probably not compatible to that add-on (please disable them or set them to browsers default value):
- disable "location bar > page 3 > favicon" ( -> location bar gets the favicon from the current tab)
- set "tabs > page 1 > appearance" to Firefox default curved tabs
- set "tabs > page 1 > position" to  tabs on top default
- disable "tabs > page 1 > tab title in Firefox titlebar"
- disable "tabs > page 2 > double click tabs toolbar opens a new tab"
- disable "tabs > page 2 > hide tabs toolbar with only one visible tab"
- disable "tabs > page 2 > new tab page url" settings
- set "tabs > page 3 > tab close > position" to default

Firefox 53 did indeed break many things and many extensions. I suggest switching to [Firefox 52.x ESR](https://www.mozilla.org/en-US/firefox/organizations/all/) for now. It will be supported up to summer 2018 and also working with legacy add-ons, while official Firefox 57+ will drop support for add-ons like CTR in November 2017.

**Comment by bongochong** [comment]
Bushels o' thanks for the tips! I've just "downgraded" to the 52 ESR version on Windows, but will be sticking with the latest Firefox releases on Ubuntu until it becomes unbearable, at which point I'll just switch to ESR releases, or Palemoon, or SeaMonkey. Anyway, after some tinkering, it's safe to say that the multiselect addon is too broken to be worthwhile on FF 53, so consider this issue resolved. CTR works great with the add-on under FF 52 though, as expected.
