### ISSUE TITLE
Low vertical webcontent size breaks website functionality [unrelated to CTR]

### ISSUE THREAD

**Issue by KirbyDE** [Aris-t2/ClassicThemeRestorer#344]
When using [UI.X](https://www.themehouse.com/xenforo/themes/ui-x) , the sticky header feature does not work when CTR is installed and the Firefox location bar is not hidden.

This effect can be seen on the following webites:
http://www.hunde-aktuell.de/
https://www.techniker-forum.de/
https://forum.foxdev.co/
http://savage.games/
http://forums.lnlpublishing.com/
https://forums.skycade.net/index.php

According to ThemeHouse support this is an issue that needs a fix in CTR.

**Comment by Aris-t2** [comment]
The **only** option, that can change anything on websites is "General UI > Page 2 > Classic image appearance on white background". All other settings are either for Firefox UI or Firefox internal "about:" pages.

"According to ThemeHouse support this is an issue that needs a fix in CTR."
How did their support come to that conclusion? What did they test?

Have you tried and tested everything described here https://github.com/Aris-t2/ClassicThemeRestorer/issues/320 (**new clean browser profile**, **only CTR** installed, **CTRs default settings**....)?

- point (sub) websites area, where the issue occurs
- post screenshots of that area with and without CTR active/installed
- (if screenshot can not show the issue properly, try to make a video)

To look into your problem I need to reproduce it, so without seeing what does not work with "sticky header feature" I can not proceed.

**Comment by KirbyDE** [comment]
"Classic image appearance on white background" is not enabled

I've tested with a fresh profile on Firefox Firefox 54.0b7 (32 Bit Windows 7) and only CTR installed without changing its settings.
The issue has also been reported by one of our users using Firefox 45 ESR on Debian, so I don't think that a specific Firefox version does make a difference.

The isusue can be reproduced on http://www.hunde-aktuell.de:
If the website is scrolled down the menu should stick on top of the page.

With CTR  and location bar enabled
![website-scolled-down-ctr](https://cloud.githubusercontent.com/assets/24271469/26011726/83968e44-3752-11e7-946b-47b4edef3f08.png)

With CTR and location bar disabled
![website-scrolled-down-ctr-noloc](https://cloud.githubusercontent.com/assets/24271469/26011747/965db80e-3752-11e7-875d-ccff79175e03.png)

Without CTR
![website-scrolled-down-noctr](https://cloud.githubusercontent.com/assets/24271469/26011768/af17a260-3752-11e7-8f32-785e6b83a0a3.png)

> How did their support come to that conclusion? What did they test?

I don't know what exactly was tested by Theme House Support/Development, but I've pointed them to this issue so maybe they can respone here directly.

> Does everything work fine without UI.X?

There is no sticky navigation without using UI.X, so I can't really give an answer here.

> How does UI.X work? Is it a theme on top of other forums?

UI.X is an Add-on for the forum software XenForo. It does provide a framework for styling and offers fearures like sticky navigation.
This is done using custom CSS, HTML templates and JavaScript for XenForo, it does not use XUL.

**Comment by Aris-t2** [comment]
So there is nothing to setup on my end? Just visiting those sites you mentioned?

If yes, then I do not have good news for you. I can not reproduce this glitch.

Tested...
... on a clean new profile
... with Firefox 52.1.1 ESR x64 / 54.0beta7 x64
... with no add-ons installed and with only CTR 1.6.6 installed
... all sites mentioned in OP

The result was always the same like in this http://www.hunde-aktuell.de example

52.1.1 ESR x64 - no CTR
![1](https://cloud.githubusercontent.com/assets/6013569/26018563/e424bbce-376f-11e7-8a15-da4b042bbff1.png)


52.1.1 ESR x64 - with CTR
![2](https://cloud.githubusercontent.com/assets/6013569/26018568/ebaacadc-376f-11e7-9cf2-ce815b52f0cd.png)


54.0beta7 x64 - no CTR
![3](https://cloud.githubusercontent.com/assets/6013569/26018572/f0761cf6-376f-11e7-9c30-4c5b52ec25d9.png)


54.0beta7 x64 - with CTR
![4](https://cloud.githubusercontent.com/assets/6013569/26018576/f3dfaac4-376f-11e7-9a9f-fec9044a41d8.png)

**Comment by Aris-t2** [comment]
The issue is related to you screen/window size and resolution. Using CTR and its squared tabs and/or add-on bar reduces/increases web contents vertical size and some website scripts do not adopt properly. This happened for some low resolutions (1366x768) with Youtube videos in the past and is also the case here. 

I can even reproduce this bug without CTR or anything else installed.
- visit one of your mentioned sites in windowed mode
- scroll down and make sure the "sticky bar" is present
- now grab your browser windows bottom edge and pull it up to decrease your window size

--> Sticky bar will disappear even in other browsers (e.g. Chrome).

This is nothing CTR can take care of.

Only UI.X devs can make sure their sticky bar does not disappear by removing the code, that actually makes it disappear.

**Comment by KirbyDE** [comment]
This sseem to be PEBCAK issue:
The minimum viewport height to show the sticky bar is actually configurable in UI.X and is set to 600 by default, which is just not enough for 1366x768 - I've got 590 with CTR and 612 without.

I am really sorry that I wasted your time.

Thank you very much for your support!
