### ISSUE TITLE
Custom private new tab page url breaks private browsing

### ISSUE THREAD

**Issue by HarveyWilliams** [Aris-t2/ClassicThemeRestorer#346]
Settings a value in CTR for the custom private new tab page url breaks private browsing - launching private browsing causes the browser to hang until an eventual "Stop script" alert comes up.

Tested on FF 53.0.3 (64-bit).

**Comment by Aris-t2** [comment]
Thanks for reporting.

Could you test CTRs latest beta and tell me, if the bug is still present?

**_CTR 1.6.7beta7_**
https://addons.mozilla.org/addon/classicthemerestorer/versions/1.6.7beta7

**Comment by HarveyWilliams** [comment]
Thanks, that worked!
