### ISSUE TITLE
[Win10] [Nightly] Tab text color issue after Fx default theme update

### ISSUE THREAD

**Issue by gelirhil** [Aris-t2/ClassicThemeRestorer#348]
Fx 55.0a1 30-05-2017 brought new browser window title and tab text default colors.
Screenshot with CTR disabled:
![1](https://cloud.githubusercontent.com/assets/24973373/26644781/8fe88c2e-463e-11e7-8111-20aab2c8d502.JPG)

Screenshot with default CTR settings:
![2](https://cloud.githubusercontent.com/assets/24973373/26644876/e2ffe826-463e-11e7-84e8-08b1fa0fe1ec.JPG)

Screenshot with `#000000` CTR color setting for default tab and hovered tab:
![3](https://cloud.githubusercontent.com/assets/24973373/26644980/469f1352-463f-11e7-8216-a0504d10305a.jpg)

Win10 with default OS theme.
Fx 55.0a1 30-05-2017+ with default theme.

**Comment by Aris-t2** [comment]
Could you test the latest CTR beta?

https://addons.mozilla.org/addon/classicthemerestorer/versions/1.6.7beta10

**Comment by gelirhil** [comment]
Fixed. Thank you.
