### ISSUE TITLE
[Unconfirmed] Nav bar buttons change from "icons+txt" to "icons-only" after every re-start

### ISSUE THREAD

**Issue by andeeII** [Aris-t2/ClassicThemeRestorer#353]
Hi!

After using FF 28 for a long time for rather nostalgic reasons (wouldn't give up "Foxscape"-AddOn UI and other features messed up by Australis UI), and on the occasion of building a new PC plus change to Win 10, I finally installed the actual FF 54, by fresh new installation and following import of settings/bookmarks etc. by "MozBackup" tool - and of course the CTR. After some hours of tinkering with the CTR settings, I had (almost) built my former look-and-feel UI - - except one issue:
I set the navigation bar buttons to "show icons and text" (<- translated from the german version), but after every restart or "close->re-open", this setting is changed to "show icons (standard)".
I suppose, this issue is CTR related 'cause IMHO FF 54 doesn't offer that button-related (icon <-> icon+text <-> textonly) settings at all..
I've temporarily deactivated all other AddOns installed, but no way..

Any clue how I could fix it or workaround or how I could perhaps "script" the FF start with this setting?

Best regards - and a huge thanks for your work!!

Andreas from Germany

**Comment by Aris-t2** [comment]
Hello Andreas,

there might be a settings conflict or something in your new profile got corrupted by "MozBackup" tool.
I suggest to test a new profile with CTR only without importing anything just to be sure.

If you are using Windows, you might want to try Portable Firefox while you are testing to not affect your current setup. Download Portable Firefox, close current Firefox, "setup" Portable Firefox and run it. Install latest CTR (beta) and switch to "icons + text" mode (-> Symbole und Text anzeigen) and restart. 

You can also write me an Email in German. ;-)

**Comment by Aris-t2** [comment]
@andeeII 
Any chance you could test what I have suggested?

**Comment by andeeII** [comment]
Hello Aris,

just sent you a mail in german, so just for the common interest:

In section **GUI** `[or what term for the german "Oberfläche" is used in the english version;-)]`, page 1, 1st line: "Small buttons on nav bar" `[or so..]`, I had forgotten to tick it on - et voilà: after restart, everything is fine!

Whatever the reason for that behaviour is.. perhaps somebody could test it on his/her system (so without any "MozBackup-influence"...

best regards

Andreas
