### ISSUE TITLE
Since FF v54  navigation bar takes a lot of space

### ISSUE THREAD

**Issue by HepoH3** [Aris-t2/ClassicThemeRestorer#354]
After update, navigation bar start take a lot of space by height. Screenshots:
before update: https://puu.sh/wy3t8.png
after update: https://puu.sh/wy3or.png
after update with disabled nav bar: https://puu.sh/wy3p6.png

**Comment by Aris-t2** [comment]
Please install CTR 1.6.8beta8 and verify the marked option is enabled, if you are using 
![1](https://user-images.githubusercontent.com/6013569/27736063-c537a402-5da2-11e7-8cc4-6bab2296c54a.png)

![2](https://user-images.githubusercontent.com/6013569/27736166-4dfcba34-5da3-11e7-90c5-209a60783a91.png)

**Comment by HepoH3** [comment]
Thank you! For some reason, after the update, the tick was removed
