### ISSUE TITLE
[Regression] After 1.6.8 update Location bar is broken with Alternative appearance

### ISSUE THREAD

**Issue by zeepob** [Aris-t2/ClassicThemeRestorer#356]
Hello, after 1.6.8 CTR update Location bar doesn't work at all when "**Alternative appearance**" option is used. It doesn't show popup and it doesn't respond for any url given (can't load any site from location bar). After unchecking that option locations bar works as expected. Also everything was normal under 1.6.7 CTR version.

There are errors in browser console like:
```
TypeError: this.richlistbox is null[Learn More]  autocomplete.xml:1103:11
	onSearchBegin chrome://global/content/bindings/autocomplete.xml:1103:11
	onSearchBegin chrome://global/content/bindings/autocomplete.xml:244:13
	onInput chrome://browser/content/urlbarBindings.xml:1124:17
	onxblinput chrome://global/content/bindings/autocomplete.xml:649:9
```
```
TypeError: this.richlistbox is null[Learn More] autocomplete.xml:1089:11
	set_selectedIndex chrome://global/content/bindings/autocomplete.xml:1089:11
	_openAutocompletePopup chrome://global/content/bindings/autocomplete.xml:1136:13
	openAutocompletePopup chrome://global/content/bindings/autocomplete.xml:1119:11
	openPopup chrome://global/content/bindings/autocomplete.xml:393:13
	set_popupOpen chrome://global/content/bindings/autocomplete.xml:103:10
	notifyResults resource://gre/components/UnifiedComplete.js:2145:5
	_addMatch resource://gre/components/UnifiedComplete.js:1757:5
	_onResultRow resource://gre/components/UnifiedComplete.js:1660:5
	_matchKnownUrl/< resource://gre/components/UnifiedComplete.js:1353:7
	handleResult resource://gre/modules/Sqlite.jsm:772:13
```
I guess it's related to below fix in new version which unfortunately works exactly opposite in my case.
> Fx54-56 & 'Location bar > AC popup > Alternative appearance': issues in some cases

Firefox: 54.0.1
OS: Linux
CTR: 1.6.8

**EDIT:** I've found that it works when "**Hide page title**" option in unchecked.

Alternative appearance **[on]** Hide page title **[off]** = **good**
Alternative appearance **[off]** Hide page title **[on]** = **good**
Alternative appearance **[on]** Hide page title **[on]** = **bad**

**Comment by Aris-t2** [comment]
Thanks, I found a typo which caused this issue for Firefox 54 only, versions 45-53 and 55-56 are fine.
In fact the "Hide page title" option is broken when combining with 'Alternative appearance'.

**Comment by Aris-t2** [comment]
Fixed version is online.

**Comment by zeepob** [comment]
It works. Thanks!
