### ISSUE TITLE
1.6.9beta3 breaks AMO on older Fx versions!

### ISSUE THREAD

**Issue by Vangelis66** [Aris-t2/ClassicThemeRestorer#359]
Hi Aris

OS: WinVistaSP2 32bit
Fx: 53.0a1 (buildID 20161117030212)
BTW, the last released version of Fx that will run on Vista is 52.0.2, 
while Mozilla have shifted XP/Vista users to Fx ESR 52.x.x (imminent release of v**52.3.0**)
CTR version: 1.6.9beta2, AOM tab settings: 
![ctr-aom](https://user-images.githubusercontent.com/9669492/28998662-929a34d4-7a39-11e7-8bcf-72313261b7a0.jpg)

When I update to latest beta **1.6.9beta3** and restart Fx, I find that AMO is totally borked: 

![aom-broken](https://user-images.githubusercontent.com/9669492/28998717-a833d452-7a3a-11e7-8f7a-fb6f4043142d.jpg)

Only User Styles tab remains unaffected and functional! (addons are not disabled though, that is NOT safe mode!). Luckily, I have a CTR preferences toolbar button (not shown in screengrab) placed in statusbar that I can access and untick `Add-on manager => Add-on lists: show add-on version` ; that way I can get a functional AMO, but, as expected, add-ons versions are not shown... 

Looking at 1.6.9beta3's changelog, I guess 
```
[fix(es)]
- Nightly and add-on managers version number option
```
is the culprit... Can you make sure this change is backwards compatible with slightly older Fx versions? 
Sadly, I can't test the effect of 1.6.9beta3 on the AMO of Fx > 52, you should check yourself which Fx versions are broken by this latest patch... Reverting to 1.6.9beta2 momentarily, until this gets sorted...

Thanks for your never waning efforts :+1:

**Comment by Aris-t2** [comment]
Thanks for reporting. 1.6.9beta4 should fix the issue.

**Comment by Vangelis66** [comment]
> 1.6.9beta4 should fix the issue

 It does so wonderfully 👍 ; and thanks for the speed by which this issue was fixed and new build uploaded on Mozilla site! You're a true gem!
Closing this.
