### ISSUE TITLE
close botton in integrated titlebar not working

### ISSUE THREAD

**Issue by hodor22** [Aris-t2/ClassicThemeRestorer#362]
win 7 - ff 55.0.2 ctr 1.6.9.1

browser.tabs.DrawInTitlebar
close botton is not working minimize and windowmode working

**Comment by Aris-t2** [comment]
Does it work without CTR? The mentioned pref is a default browser pref and not related to CTR. You only see an additional switch for it on CTRs prefwindow.

**Comment by Aris-t2** [comment]
Closing as there was no answer and the bug could not be reproduced by me.
