### ISSUE TITLE
About the theme

### ISSUE THREAD

**Issue by WagnerGMD** [Aris-t2/ClassicThemeRestorer#366]
`pref("lightweightThemes.selectedThemeID",'firefox-compact-dark@mozilla.org');`
Hello,

after the installation (of Classic Theme Restorer_v1.7.0), I had notice one little trouble on the page **about:addons**. Then I'm wonder if it won't be better to avoid it ? At least if there is one way to detect it ? I don't have a clue about.

Kind regards.

PS : Because yes it easy to correct but I will assume the theme shoudn't be altered (or modify on the left side).
In fact, it's a little worst with the current **Nightly** (aka Firefox_v57) but perhaps it could be fix with the addon CTR ? That's just a suggestion ~~(and Mozilla should really rename it damn it. Because no there aren't the same theme and I dislike it).~~

**Comment by Aris-t2** [comment]
Hi,

can you specify the actual issue on about:addons? Page colors? Fonts? Something else? Try to disable CTRs 'alternative appearance for add-ons page'.
CTR preferences > Add-ons page > Alternative appearance

Firefox 57+ does not support legacy add-ons like CTR. There won't be any changes in CTR for Fx57+ anymore. See https://github.com/Aris-t2/ClassicThemeRestorer/issues/299

To use CTR after Firefox 57 release you can only move to a different browser version Firefox 52ESR or a Firefox fork like Waterfox 55. The first one supports legacy add-ons up to summer 2018 and the later one indefinitely ar at least much longer.

**Comment by WagnerGMD** [comment]
Hi,

apparently, it's about the color and in fact, it (the menu) should be like on this picture : ![RightColorTheme_BrowserFirefox](http://nsa39.casimages.com/img/2017/09/20/170920041640199741.png)![NotRightColorTheme_BrowserFirefox](http://nsa39.casimages.com/img/2017/09/20/17092004164024385.png)
Tio precise, it's the first one on the left.
And you're right. Because in my previous post I was refering to the Alternative appearance (like I said it was easy to find).

**PS :** No problem and thank you for the confirmation. For now, I don't have any plan but I will need to find a way to keep (or export) the current theme **Compact-Dark**.
`pref("extensions.legacy.enabled";true)`
I imagine the addon maybe will work if this settings still remain. Do you know where is located the theme ? Do you think you can add a function to export (and import) the theme ? Because it's seem that Mozilla won't keep the same theme and would rather to find a solution to keep it. If you have any idea.

**Comment by Aris-t2** [comment]
The add-on manager colors on the left of your picture is the default one for every theme (default, compact light/dark) in Firefox up to 56. 

I can not add "something to export internal themes" to CTR, but you can extract all the code using Winrar or 7zip.

Navigate to you browsers installation folder and look for
\omni.ja 
\browser\omni.ja


Copy those files to a different location, rename them to jar or zip and extract them with Winrar or 7zip.

Add-on manager code:
\omni.ja\chrome\toolkit\skin\classic\mozapps\extensions\extensions.css
Compact theme code:
\browser\omni.ja\chrome\browser\skin\classic\browser\compacttheme.css

Even with **extensions.legacy.enabled** set to **true** most of CTRs features do not work and trying to support them on Nightly channel only is not worth the effort anyway.

**Comment by Aris-t2** [comment]
Is the issue solved or still present?

**Comment by Aris-t2** [comment]
Closed due to no further response.
