### ISSUE TITLE
How to apply the default weaks with WebExtensions?

### ISSUE THREAD

**Issue by rfgamaral** [Aris-t2/ClassicThemeRestorer#369]
Looking at #365 I've noticed:

> Available by default (without WebExtensions)

But where are these tweaks available? What does it mean that they are "available by default"?

For instance, I'm using the Nightly and I'd love to reconnect the back/forward buttons to the location bar (and only show the forward button if forward history is available) and to combine stop/reload buttons inside the location bar.

Are these tweaks possible by tweaking `userChrome.css`? Any tips on where I should begin?

**Comment by Aris-t2** [comment]
Like mentioned in #365 everything I have tested so far will be available later. Nothing is online yet.

> CSS modifications for userChrome.css will be uploaded to Github once we get closer to Firefox 57s official release date.

"Available by default" means these features are part of Firefox 57+ now, but were not in the past (Firefox 29-56) without add-ons.

You can hide disabled buttons like the forward button, but the overlapping with location bar is not part of Firefox anymore. Maybe it is possible, I haven't tested.

![1](https://user-images.githubusercontent.com/6013569/30646339-f3e470ee-9e18-11e7-916a-f69e10f5ebfb.png)
