### ISSUE TITLE
Oversized icons in latest Nightly in hi-dpi mode

### ISSUE THREAD

**Issue by LordJZ** [Aris-t2/ClassicThemeRestorer#37]
Navigation bar icons: Star, Bookmark, RSS, Downloads, Encoding displayed in double size. On the contrary, Back, Forward, Reload, Hello, Hamburger icons are displayed correctly.

**Comment by Aris-t2** [comment]
I will upload a new beta build (1.3.2beta1) to fix Nightly icon bug soon.

**Comment by LordJZ** [comment]
Confirmed working, but now these buttons are much wider:
![untitled](https://cloud.githubusercontent.com/assets/32092/7441000/736cb96c-f0dc-11e4-80b2-deae07dedde1.png)
![untitled](https://cloud.githubusercontent.com/assets/32092/7441006/911b01f8-f0dc-11e4-966b-0483a22bb8d4.png)

**Comment by Aris-t2** [comment]
Switch to OS default dpi value (-> 100%).

Changelog:

[fix] Windows + Fx40+: icon size of some buttons
--> non-default OS dpi settings + small buttons mode + Fx40+ will
--> increase button width as result of that fix

Mozilla is currently changing the way icons/button are handled, so this is maybe not the last thing that breaks during that process.

**Comment by crazymykl** [comment]
When the bookmark star is set to be within the location bar, it is made huge.

**Comment by Aris-t2** [comment]
OS?
OS version?
OS dpi value?
Firefox version?
CTR version?
Screenshot?
;-)

**Comment by crazymykl** [comment]
Mac OS 10.10.3 (Yosemite)
FF 40.0a2
CTR 1.3.2

![screen shot 2015-05-19 at 3 50 40 pm](https://cloud.githubusercontent.com/assets/234584/7712363/0184a60a-fe3f-11e4-9ba1-f427e14dedfa.png)

**Comment by Aris-t2** [comment]
I see, HiDPI mode...

Install latest beta and report back: https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by crazymykl** [comment]
Looks good on the new beta :+1:.

**Comment by LordJZ** [comment]
So the increased width icons have made it into Aurora channel. Any update on this from CTR?

**Comment by Aris-t2** [comment]
Same problem as before or a new one?

![untitled](https://cloud.githubusercontent.com/assets/32092/7441000/736cb96c-f0dc-11e4-80b2-deae07dedde1.png)

**Comment by LordJZ** [comment]
Exactly https://github.com/Aris-t2/ClassicThemeRestorer/issues/37#issuecomment-98351357

**Comment by Aris-t2** [comment]
Could you test this build?
https://www.dropbox.com/s/oojd0ph5khy9xcq/CTR_v1.3.3r20.xpi?dl=0

**Comment by LordJZ** [comment]
The icons got just a little bit smaller, but noticeably narrower in FF 41, CTR r21 with 200%:
![ff38](https://cloud.githubusercontent.com/assets/32092/7788574/70cd19d0-0249-11e5-9721-71ff6e71340e.png) Firefox 38, any CTR
![ff41](https://cloud.githubusercontent.com/assets/32092/7788580/8546087c-0249-11e5-9add-c6c2b7d555f7.png) Firefox 41, CTR r21

Still much better than before, thanks!

**Comment by Aris-t2** [comment]
Fx38 only uses one small icon set known from Fx4-39, while Fx40+ uses a big one for high dpi values (110%+) and the small one for 100% and smaller resolutions.

**Comment by LordJZ** [comment]
Well you can overlay the two images above to see the "refresh" button height was 30 machine pixels in FF 38, and 26 machine pixels in FF 41. That icon didn't change, so it's not about different icons, it's about rescaling.

Additional evidence is the "bookmark panel" icon. You can clearly see on the bottom border that it is not rendered pixel-perfectly like the [actual icon](https://raw.githubusercontent.com/mozilla/gecko-dev/master/browser/themes/windows/Toolbar%402x.png) is. And it is in fact rendered correctly without CTR. So it's CTR messing with icon sizes, scaling them a little and making them blurry.

Additionally, it looks like all icons except Firefox Hello have 2x versions (see link above), so it would be nice to use them in high-dpi mode.

**Comment by Aris-t2** [comment]
The refresh icon is not a good example, as only the "default" buttons use hires images yet, but not the ones added by CTR. I will add available hi res icons to them later.

We are talking about "small button mode" only, right? No everything is perfect atm.

**Comment by LordJZ** [comment]
I am always on small button mode, haven't tested other modes. I can do some testing for you if you want.

**Comment by Aris-t2** [comment]
I will try to improve small button mode over time. I can't tell an eta, but it is planned to rebuild it from the scratch. 

Next build will offer hi res icons for movable back/forward, stop, reload and history buttons (Windows + 110%+ dpi values), because default Fx icons are present for these CTR buttons.

**Comment by LordJZ** [comment]
Thanks, keep up the good work :)
