### ISSUE TITLE
Some icons on the toolbar gets larger then others

### ISSUE THREAD

**Issue by 476210180** [Aris-t2/ClassicThemeRestorer#370]
OS version: Windows 10 Pro 64bit build 15063 (EDIT: as the CTR author mentioned in beta 4 change log, os is 125% dpi)
Firefox version: 55.0.3 stable 64bit
CTR version: 1.7.1 beta2 (also tried CTR 1.7.0 before)
![default](https://user-images.githubusercontent.com/8447650/30910932-42f8b424-a3b9-11e7-9189-a0096e289bc6.PNG)
the 'uBlock Origin' icon and the 'HTTPS Everywhere' icon is larger than other icons, which made me very annoying....
on my other laptop with same configurations the 'uBlock Origin' icon is normal but the 'HTTPS Everywhere' icon is larger too.
the config file of CTR is in the zip file attached.

[CTRpreferences.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/1336881/CTRpreferences.zip)
_pls forgive my bad english because i'm not familiar with it :)_

**Comment by Aris-t2** [comment]
I just have posted a new CTR beta. Could you install it and tell me, if the issue is still present or not?

**Comment by 476210180** [comment]
solved, but the greasemonkey icon gets really small
![default](https://user-images.githubusercontent.com/8447650/30942874-fae0d600-a41f-11e7-8465-b4e127296b62.png)
and my laptop still have huge icons (normal dpi)

**Comment by Aris-t2** [comment]
Which HiDPI values are set on your devices?

**Comment by 476210180** [comment]
I have 125% DPI on Windows 10(desktop), normal(default) DPI on Windows
7(laptop).

2017年9月28日 下午2:17，"Aris" <notifications@github.com>写道：

**Comment by 476210180** [comment]
I have tried beta 5 and it's all fixed, both my desktop and my laptop.
Thanks!!
Win 10:
![default](https://user-images.githubusercontent.com/8447650/31010776-95644a1c-a53e-11e7-8241-380b2ef772f4.png)
Win 7:
![2](https://user-images.githubusercontent.com/8447650/31010870-fb2d2774-a53e-11e7-8b09-970e77cc0a57.GIF)
