### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by cusn** [Aris-t2/ClassicThemeRestorer#371]
Search Bar has no Old Search in Firefox56，Can it be added?

**Comment by Aris-t2** [comment]
No, 'old search' does not work on Firefox 56 the way it did before and got removed.
Try Firefox 52 ESR or Waterfox 55.x, it works on both.

**Comment by Aris-t2** [comment]
I could restore the old search for Firefox 56 in latest CTR beta.

https://addons.mozilla.org/addon/classicthemerestorer/versions/beta

**Comment by cusn** [comment]
Thank you very mach!
