### ISSUE TITLE
addon symbols disappearing

### ISSUE THREAD

**Issue by hodor22** [Aris-t2/ClassicThemeRestorer#374]
win7 64, firefox 56 , ctr 1.7.1
this happend after update from ctr 1.6.8.1 to 1.7.1.
Every time I restart Firefox the 2 icons for twitchfox and liverstreamer addon disappear. I have to reload old settings for ctr in a .json and they will come back after a restart. But If I close the Browser , they are gone forever. Disabling ctr brings them back permanently. 

![ctr](https://user-images.githubusercontent.com/10690055/31166962-d05fbd30-a8f0-11e7-9159-776545838c55.jpg)

**Comment by Aris-t2** [comment]
When did this started to happen, after CTR 1.7.1 release?
Does this happen, if only CTR on those two add-ons are active?

**Comment by hodor22** [comment]
it happened right after installing ctr 1.7.1 and restart . also when I move tabs from ontop to under adressbar in ctr the symbols are also gone

**Comment by Aris-t2** [comment]
I can only repeat what I said before, run tests in a clean new environment with only CTR, liverstreamer and Twitch Fox installed. That is what I did and I never saw a livestreamer button with or without CTR and Twitch Fox button is always visible with and without CTR, with and without tabs on top.

![2](https://user-images.githubusercontent.com/6013569/31187196-6e805f70-a931-11e7-9eb1-113541c9a9e8.png)

**Comment by Aris-t2** [comment]
@hodor22 

Any test results from your side?
