### ISSUE TITLE
[Win10][Fx56][add-on compatibility][Xmarks] Blank pop-ups after clicking 'Sign in' button

### ISSUE THREAD

**Issue by coolio1** [Aris-t2/ClassicThemeRestorer#375]
I have discovered that CTR prevents some pop-ups from displaying correctly. For example, pop-ups of Xmarks appear blank when CTR is enabled, but they work when CTR is disabled. This prevents me from sync my bookmarks.

**Comment by Aris-t2** [comment]
This is not enough context, see here: https://github.com/Aris-t2/ClassicThemeRestorer/issues/320

Looks like this for me on Fx 56 in a clean new browser profile.
![1](https://user-images.githubusercontent.com/6013569/32146314-bb70ff8a-bcd5-11e7-8c47-f5c29d49860c.png)

**Comment by coolio1** [comment]
Sorry for the lack of info. In fact that window I can see, it's afterwards that they get blank. See below. When I click on "sign in" the pop-up appears blank and I cannot do anything else.

![capture](https://user-images.githubusercontent.com/33202549/32146661-0f6588c2-bcdb-11e7-9707-22bf82a9da34.JPG)

**Comment by Aris-t2** [comment]
Setup a new browser profile (or test Portable Firefox) and only install CTR and Xmarks.
(Also test default CTR settings on your current setup)

![1](https://user-images.githubusercontent.com/6013569/32147058-f7bd30c0-bce0-11e7-8463-6080eff2e5f6.png)

**Comment by Aris-t2** [comment]
I close this since there was no further respond and the issue did not occur for me.
