### ISSUE TITLE
#nav-bar[iconsize='large'] setting is not compatible with svg icon of WebExtensions

### ISSUE THREAD

**Issue by magicp-github** [Aris-t2/ClassicThemeRestorer#377]
**Steps to reproduce:**
1. Launch Firefox 56 with CTR 1.7.2
2. Load Add-on "Permissions  Example" (https://github.com/mdn/webextensions-examples/tree/master/permissions)
3. Set #nav-bar[iconsize='large']

**Actual Results:**
Add-on Icon is too large. Firefox Screenshots icon too.
![ctr](https://user-images.githubusercontent.com/13914314/32611458-163cc1de-c5a9-11e7-9d0c-0ee5d05bfea5.png)

**Expected Results:**
Set max-width (24px?)

**Comment by Aris-t2** [comment]
Any AMO add-ons affected?

**Comment by magicp-github** [comment]
Yes.
![emoji](https://user-images.githubusercontent.com/13914314/32618038-e6c65c1a-c5b9-11e7-906c-a3c295a7777e.png)

**Comment by Aris-t2** [comment]
The fix will be in next beta and release versions.

**Comment by Aris-t2** [comment]
Fixed in CTR 1.7.3
