### ISSUE TITLE
"Add-on lists: show add-on version" conflicts with http://bugzil.la/612168

### ISSUE THREAD

**Issue by JustOff** [Aris-t2/ClassicThemeRestorer#381]
When `Add-on lists: show add-on version` is enabled in Firefox 47-56, then changes introduced by [bug 612168](https://bugzilla.mozilla.org/show_bug.cgi?id=612168) are overwritten and restartless add-ons are never received the `ADDON_UNINSTALL` reason on uninstall, but `ADDON_DISABLE` (see [bug 620541](https://bugzilla.mozilla.org/show_bug.cgi?id=620541)).

Here is test add-on: [uninstall-test@Off.JustOff.xpi.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/1491271/uninstall-test.Off.JustOff.xpi.zip)

**Comment by Aris-t2** [comment]
I ran some tests on Firefox 56 and the add-on gets uninstalled identically with and without version number being active. The add-on does not get disabled when you uninstall it, so I have no idea what issue this might cause even, if it fires up the wrong reason. Extension page has to be reloaded/reopened for the add-on to disappear in both cases.


![1](https://user-images.githubusercontent.com/6013569/33076305-ac974d44-cecc-11e7-99ed-afc8ba925cfd.png)

![2](https://user-images.githubusercontent.com/6013569/33076309-aee51dc4-cecc-11e7-9b76-2cea52d61e97.png)

**Comment by JustOff** [comment]
Please run test add-on attached above and you will see that when `Add-on lists: show add-on version` is on, then both Disable and Remove results to [ADDON_DISABLE](https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions#Reason_constants) reason and never `ADDON_UNINSTALL`.

**Comment by Aris-t2** [comment]
OK, I found what is causing this and will offer a fix on next update.

This was no real problem anyway. Look into default xml files uninstall method from Fx56:

> // If uninstalling does not require a restart and the type doesn't
> // support undoing of restartless uninstalls, then we fake it by
> // just disabling it it, and doing the real uninstall later.

**Comment by JustOff** [comment]
> OK, I found what is causing this and will offer a fix on next update.

Thank you!

> This was no real problem anyway.

Actually it is a problem, because if an extension performs some cleanup on uninstall it will never be called, and that's how I found it.

**Comment by Aris-t2** [comment]
Install this beta https://addons.mozilla.org/de/firefox/addon/classicthemerestorer/versions/1.7.3.2beta2

**Comment by JustOff** [comment]
I confirm 1.7.3.2beta2 fixes the problem, tested with FF 52.5.0 ESR & Basilisk M1.
