### ISSUE TITLE
Firefox 57 ClassicThemeRestorer an idea

### ISSUE THREAD

**Issue by ghost** [Aris-t2/ClassicThemeRestorer#382]
OK i know Mozilla SUCK and Firefox will be dead in few years

But what about create "ClassicThemeRestorer" base on [ XULRunner](https://en.wikipedia.org/wiki/XULRunner):

- So you can still use XUL language but custom CSS file will be write to user_profile by exe application

https://github.com/Aris-t2/CustomCSSforFx

https://en.wikipedia.org/wiki/XULRunner

**Comment by RobertZenz** [comment]
See [this comment](https://github.com/Aris-t2/ClassicThemeRestorer/issues/380#issuecomment-344667312).

**Comment by Aris-t2** [comment]
Wasn't XULRunner discontinued years ago?

Anyway, we have good alternatives like Waterfox and Basilisk to keep legacy add-ons running.
There is no need for software that hacks CTR features into Firefox 57+.
