### ISSUE TITLE
[Win][Waterfox56]Customize toolbars doesn't retain elements moved in toolbars

### ISSUE THREAD

**Issue by remez** [Aris-t2/ClassicThemeRestorer#384]
Hello,
I need to customize my toolbars adding a fixed space or other elements added by the CTR.
I go in "Hamburger" -> "Customize"
In the "Additional Tools And Features" Windows I see some elements that I want to move to my toolbars.
If I try to move "Space" or "Separator" or "Flexible Space" in any toolbar, when I release the left button of the mouse, the element isn't inserted in the toolbar.

Configuration:
Windows 7 64 bit
Waterfox 56.0 64bit English
Default Theme
Tried with a clean installation of Waterfox and CTR (last Official version and last beta)

Thank you

**Comment by Aris-t2** [comment]
Spaces, flexible spaces and separators don't work in Firefox/Waterfox 56 anymore.

https://github.com/Aris-t2/ClassicThemeRestorer/issues/383

**Comment by remez** [comment]
Thank you.
The strange thing is thet if I import a old Firefox profile (older than V56) with spaces and separators in the toolbar, these spaces and separators are retained...

**Comment by Telmesomething** [comment]
@ remez,

You could consider switching to [Basilisk](https://www.basilisk-browser.org/) (created by the Pale Moon team) which is based on Firefox 55 and supports CTR separators and spaces. I've been using it for a couple of weeks now without any issues. Here's a pix of CTR spaces added to the toolbar. 

![spaces_toolbar](https://user-images.githubusercontent.com/33827636/33833656-9c06dee0-de80-11e7-93df-2ac890f448fb.PNG)

**Comment by remez** [comment]
Oh, thank you for the info, I will try it!

**Comment by Telmesomething** [comment]
> Oh, thank you for the info, I will try it!

Only downside is that Basilisk can't import your FF/Waterfox profile so you have to install everything from scratch. But you can drag and drop the XPI files from your profile folder rather than having to download them all over again. 

If you use Video Downloadhelper, install the Beta mentioned in [this article](https://www.downloadhelper.net/q_and_a_firefox) otherwise the toobar button doesn't appear.

**Comment by Aris-t2** [comment]
Closed, because we have two threads about this issue:
https://github.com/Aris-t2/ClassicThemeRestorer/issues/383
