### ISSUE TITLE
Need option to remove search bar in Waterfox

### ISSUE THREAD

**Issue by Telmesomething** [Aris-t2/ClassicThemeRestorer#385]
Hi Aris,

Would it be possible to add an option to CTR to remove the search bar which pops up in Waterfox below the location bar results every time a URL has been typed in it? Here's an image of what I'm talking about.

![how to remove search options](https://user-images.githubusercontent.com/33827636/34905529-d0b6c77e-f85a-11e7-8692-e795b6d0aac3.PNG)

I'm sure the Waterfox developer means well, but why would I want to use a search engine to search for a site I already have the URL for. It just gets irritating after a while.

**Comment by Aris-t2** [comment]
Already present for a long time.

CTR preference window > Location bar > Autocomplete popup > show search engines

**Comment by Telmesomething** [comment]
> Already present for a long time.

> CTR preference window > Location bar > Autocomplete popup > show search engines

Magic! Thanks Aris. 

P.S. I really did look around the menus first, but the autopopup option didn't catch my eye for some strange reason.
