### ISSUE TITLE
[Basilisk browser] Spaces added to toolbar no longer movable

### ISSUE THREAD

**Issue by Telmesomething** [Aris-t2/ClassicThemeRestorer#386]
As per the title spaces added to the toolbar in Basilisk cannot be moved anymore. Attempting to move them just moves the whole window now. 

A workaround for this particular problem is to add two (or more) of them to the toolbar and then to move the button(s) in between them. Repeat as necessary to reposition buttons as desired.

**Comment by Aris-t2** [comment]
Which toolbar are your spaces on and are they movable, if you enable/disable the titlebar in customizing mode.

I just tested Basilisk (2018-01-05) x64 (Win7x64) and all spaces, flexible spaces and separators on menubar, tabs toolbar, navigation toolbar, bookmarks toolbar and add-on bar are movable in customizing mode.

**Comment by Telmesomething** [comment]
> Which toolbar are your spaces on and are they movable, if you enable/disable the titlebar in customizing mode.

Standard toolbar i.e. to the left and right of the location bar. 
![can t_move_spaces](https://user-images.githubusercontent.com/33827636/35624338-feccaf2e-068e-11e8-9d7e-4cb4ba5556f1.PNG)


The only thing that's been changed is NoSquint Plus has been removed. According to various reviews of it on the [Moz site ](https://addons.mozilla.org/en-US/firefox/addon/nosquint-plus/) the developer regularly adds expiration dates to older versions which causes it to stop working even after updating it to the latest version. I don't know if that would cause the non-movable separators problem though.

**Comment by Aris-t2** [comment]
You could try to reset your toolbar configuration by hitting "Restore defaults" button in customizing mode.

Also reset this preference: about:config > browser.uiCustomization.state

Removing add-ons should not break toolbar configuration like this.

**Comment by Telmesomething** [comment]
Well, I just created a new profile and only installed CTR, but the problem persists. The only difference between us is that I'm running Windows 8.1

**Comment by Telmesomething** [comment]
> Also reset this preference: about:config > browser.uiCustomization.state

I just tried that, but no change. 

I'll go disable my AV now to see if that's the cause.

**Comment by Telmesomething** [comment]
I found the cause of the problem which as nothing to do with AV.

Simply put, there's no need to move spaces, separators etc. Just drag & drop them from the customization menu and place them where you wish. They seem to stay put now. :)

**Comment by Aris-t2** [comment]
Good to hear you solved this issue.

Out of curiosity I setup Basilisk and a new profile with CTR in Win8.1. No issue moving or drag&drop them anywhere.

![basilisk](https://user-images.githubusercontent.com/6013569/35626868-5a7f4590-0697-11e8-8652-e4f96cea58cd.png)

**Comment by Telmesomething** [comment]
Weird. They still can't be moved on my new profile. Also, after installing CTR on it, the back and forward buttons were missing. 

![new_profile_no_back-forward-buttons](https://user-images.githubusercontent.com/33827636/35628317-d6a67d9c-069b-11e8-802b-b18c4ed85ba0.PNG)

No problem really since I could drag & drop those from the customization menu.

**Comment by Aris-t2** [comment]
Not sure, but how exactly do your create a new profile?
After creating one and installing CTR it has to look like on my screenshot. Yours already shows a bunch of active (CTR) settings. The goal behind creating new profiles is testing browsers default environment without any setting changes.

**Comment by Telmesomething** [comment]
I just follow standard practice as described [here ](http://kb.mozillazine.org/Creating_a_new_Firefox_profile_on_Windows) with the exception that firefox.exe -p is replaced with basilisk.exe -p 

I usually name the new profile with something which represents whatever the problem is.

**Comment by Aris-t2** [comment]
> The only other change is to import CTR settings used in another profile which isn't experiencing any problems.

That is one of the main problems, that can occur and jeopardize new profile tests completely. There are tons of setting changes over different browser versions. Importing an "older" configuration not only adds add-on leftovers, but also toolbar configurations and errors saved inside previous about:config preferences. 
 
A new profile means renaming / backing up the current profile folder and starting from 0 (downloading and configuring add-ons, configuring browser settings).

**Comment by Telmesomething** [comment]
Well, not really since I always export CTR settings from an existing profile before importing them into a new one. So in that respect, the settings will be the same. 

What you're suggesting will be both time consuming and impractical since it will mean recreating all the settings all over again from scratch. There won't be much point in creating a CTR backup if it can't be used again.

**Comment by Aris-t2** [comment]
Creating a new profile for testing should not be comfortable, fast or practical. The only purpose is testing a clean environment, which gets jeopardized by importing anything from a previous profile.

Again this is for testing only until confirming whether the error is present on a clean new profile or not. Afterwards things can be imported and tested further. This is the only way two or more users can compare setups and find what probably is causing an error.

**Comment by Telmesomething** [comment]
>  Creating a new profile for testing should not be comfortable, fast or practical. The only purpose is testing a clean environment, which gets jeopardized by importing anything from a previous profile.

Well, I suppose you have a point there so I created another new profile and then installed CTR in its bare bones state. This time spaces are indeed movable. 

So here's the offending CTR prefs file which contains something which is causing that problem.
[CTRpreferences.txt](https://github.com/Aris-t2/ClassicThemeRestorer/files/1685383/CTRpreferences.txt)

**Comment by Telmesomething** [comment]
I'll save you the trouble of looking for it. The problem arises when tabs are moved below the location bar. The actual setting is "Tabs not on top V2".

**Comment by Aris-t2** [comment]
There is an easy solution, only use **Tabs not on top v1**.

![1](https://user-images.githubusercontent.com/6013569/35679618-009ba6ba-0758-11e8-80a6-084658e236d7.png)

**Comment by Telmesomething** [comment]
> There is an easy solution, only use Tabs not on top v1.

Appreciate the response but it's not really necessary because spaces can be added simply by placing them via drag&drop. But I just thought I'd mention in my previous post that tabs below the location bar seemed to be the cause of the problem (to save you searching for it). 

I notice though that V1 adds an additional spacing line between the menu bar and the location bar/addon buttons. I can't remember why I selected V2 before since it's too long ago. But I'll keep the V1 solution in mind just in case things go pear-shaped again.  :)

Thanks for your help Aris.
