### ISSUE TITLE
CTR for Android?

### ISSUE THREAD

**Issue by LafinJack** [Aris-t2/ClassicThemeRestorer#387]
Hi there, just wondering how much interest/effort would be involved in making CTR available for Firefox/Waterfox >56. Currently Firefox Android is at 58.0.2, but I intend to follow Waterfox, the Android version of which is currently at 55.0.2, though working towards 56 parity from what I understand. 

Lowest possible priority, please, I know things are a bit hectic lately. :)

**Comment by Aris-t2** [comment]
Firefox for Android does not allow any ui changes, one can not style or change tabs, toolbars or buttons. Older Firefox for Android versions did not support any ui tweaks or ui changing add-ons either.

[Most CTR features are available for Firefox 57+ (PC/Desktop through) userChrome.css CSS tweaks.](https://github.com/Aris-t2/CustomCSSforFx/issues/2)

**Comment by LafinJack** [comment]
Doh! Thank you, though!
