### ISSUE TITLE
[old search][Waterfox 56.2] Alt-down stopped opening search engine list

### ISSUE THREAD

**Issue by don-reba** [Aris-t2/ClassicThemeRestorer#390]
Alt-down used to open the search engine list in the old-style search bar, and it still does in the default, new version. But this shortcut no longer does anything in the old-style search bar, as of the last (or a very recent) update.

Waterfox 56.2.0 (64-bit)

**Comment by Aris-t2** [comment]
Are you sure  "Alt-down" feature was done by CTR? I don't recall seeing this feature ever in CTR. 

I tested Firefox 52 ESR and Firefox 56 and both did not offer such a feature with CTR 1.7.4. You can however switch between search engines with Ctrl+Up/Down.

**Comment by sasoph** [comment]
Firefox 52 ESR (52.8.0esr-1) 64-bit: ALT+Down used to work with CTR **pre** 1.7.4.

With 1.7.4 and old search, ALT+down just shows previous search terms.

CTRL+Up/Down is no use, as cycling through all my search forms (many sites not just engines) one by one is, is tedious.

**Comment by sasoph** [comment]
1.7.4.1 restores Alt+Down.

Cheers.

**Comment by don-reba** [comment]
With 16 search providers, my main mode of operation was pressing Ctrl-E to focus on the search bar, then Alt-Down and the first letter of the search engine's name. Now I have to press Ctrl-Down up to 15 times to get the engine I need.

**Comment by don-reba** [comment]
Can confirm the problem is fixed in 1.7.4.1.
