### ISSUE TITLE
How to change the CTR menu background settings colors to white

### ISSUE THREAD

**Issue by Telmesomething** [Aris-t2/ClassicThemeRestorer#393]
I know you mean well Aris, but the new CTR menu background colors to the settings menus really makes them difficult to read if your eyesight isn't up to scratch. Is there some way of changing them all back to a plain white background, preferably in one go?

**Comment by Aris-t2** [comment]
Post a screenshot.
I don't recall changing color on purpose there.

**Comment by Telmesomething** [comment]
> Post a screenshot.

Maybe it's down to Waterfox then, but this is how the menus appear now.
![menu_colors](https://user-images.githubusercontent.com/33827636/40912094-e860ba0a-67f0-11e8-81c8-bd7e705df930.PNG)

**Comment by Aris-t2** [comment]
It sounded like you were talking about a different area. The colors can be disabled on "Classic Theme Restorer" tab. They are mainly for users to see what future browser versions can offer with user scripts (CSS or JS).

![1](https://user-images.githubusercontent.com/6013569/40912807-f2429140-67f2-11e8-8cf3-80faebd42939.png)

**Comment by Telmesomething** [comment]
Magic! Thanks for the prompt response Aris.
