### ISSUE TITLE
Latest CTR version 1.7.7.2 prevents home page from displaying correctly

### ISSUE THREAD

**Issue by Telmesomething** [Aris-t2/ClassicThemeRestorer#394]
After updating to CTR 1.7.7.2 the Home button no longer loads my home page which is a blank page. Here are some screenshots to illustrate the problem. 

The first one shows the Guardian UK site of which the page title appears on the tab. 
![ctr_before_clicking_home_button](https://user-images.githubusercontent.com/33827636/42932957-ede165c6-8b43-11e8-8c2f-b7189cb1c91b.PNG)

The next one shows what happens when I click the Home button. The site remains onscreen even though the page title reverts to "New tab". 
![ctr_after_clicking_home_button](https://user-images.githubusercontent.com/33827636/42933027-13b7b714-8b44-11e8-89f2-b15e854d58b4.PNG)

Right clicking the back button shows that the home page should have loaded, but hasn't. 
![ctr_about_blank](https://user-images.githubusercontent.com/33827636/42933181-713c813a-8b44-11e8-9b43-0aa0dd49bbe1.PNG)

**Comment by Telmesomething** [comment]
Oh damn...

It's not CTR which is causing the problem but an update to Canvas Blocker. When I disabled that, CTR works as it normally does. 

Apologies Aris!

**Comment by Aris-t2** [comment]
OK ;-)
