### ISSUE TITLE
Export preferences (txt) adds checkmark to "Show search engines" in new Waterfox profile

### ISSUE THREAD

**Issue by Telmesomething** [Aris-t2/ClassicThemeRestorer#397]
Hi Aris,

Exporting preferences (txt) and then importing same into a new Waterfox profile adds the checkmark to "Show search engines" in the Location Bar/Autocomplete popup menu.

Steps to reproduce.

1. Export prefs in txt format from an existing profile. 
2. Run: waterfox.exe -p 
3. Create new profile.
4. Install CTR using drag&drop from the extensions menu in the old profile.
5. Ensure that "Provide search suggestions" and "Show search suggestions in location bar results" are both unchecked in `about:preferences#search`
6. Import prefs file created in step 1. 
7. Perform a search for something using the location bar.  

In my particular case, "Search with..." appeared at the foot of the results as per the image due to the checkmark being added to the "Show search engines" setting even though it had been removed in the old profile. All other settings seemed to have imported correctly. 

EDIT: OS is Windows 8.1 fully patched. 

![search_with](https://user-images.githubusercontent.com/33827636/45864116-399bbb80-bd79-11e8-955c-bfef29f891b9.PNG)

**Comment by Aris-t2** [comment]
This is a misunderstanding. The bottom search content of location bars popup is not covered by CTRs import/export features. The corresponding switch gets triggered by browsers default/internal preference `about:config >>> browser.urlbar.oneOffSearches`.

On a new profile this preference is enabled by default.

When you export settings in CTR a warning sign gets displayed on the left stating '`about:config >>> ...' preferences do not get exported or imported by CTR. This is done on purpose as importing default browser settings requires a settings access level higher than own add-on settings level. Mozilla refused to allow that back then.
