### ISSUE TITLE
Add-on Bar always reappears upon restart.

### ISSUE THREAD

**Issue by Peacock365** [Aris-t2/ClassicThemeRestorer#405]
As the title always says, the Add.on Bar always reappears upon browser restart, even if it was turned off via _View --> Toolbar --> Add-on Bar_.

**Waterfox 56.2.9
Classic Theme Restorer 1.7.8.2019.02.10
macOS 10.14.4 Mojave**

It should be noted that this behavior happens when one of the new WebExtension lightweight themes is used, here is such a theme:

https://addons.mozilla.org/de/firefox/addon/dark/?src=search

It should also be noted that the Add-on Bar is blacked out when such a theme is used, as if the theme is not being applied to it at all.

Please fix.

**Comment by Aris-t2** [comment]
I cannot confirm this. In my tests the add-on bar does not reoccur after restart. Try to create a new browser profile and only install CTR.

**Waterfox 56.2.9
Classic Theme Restorer 1.7.8.2019.02.10
macOS 10.14.4 Mojave**
**Dark theme**: https://addons.mozilla.org/de/firefox/addon/dark/

![wf](https://user-images.githubusercontent.com/6013569/56467353-0956f100-641e-11e9-8c01-98363e391b32.png)


(I can only test this in a VM, no Apple Hardware around here ;-))

**Comment by Peacock365** [comment]
Never mind, in my case it does reappear every time I restart the browser, even if it was turned off before the restart takes place. Seems like a bug specific to my setup, eh?

I don't mind it, it is not a general bug of the add-on, and Waterfox will switch to a Firefox 68 ESR base in the mid-term anyway. By the way, do you plan to update the add-on for Waterfox 68? From the Waterfox subreddit, I know that Alex did implement all changes of the Thunderbird team to ensure the continued compatibility of bootstrapped add-ons:

- https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63
- https://thunderbird-webextensions.readthedocs.io/en/latest/how-to/extensions68.html

Waterfox 68 will also support WebExtensions Experiments by default. Will CTR be possible still?

**Comment by Aris-t2** [comment]
If only bootstrapped add-ons will run on WF68+, then CTR won't be able to, because it only is an oldschool overlay add-on.

Many CTR features can be ported or recreated using bootstrapped add-ons, but I don't think I'm going to spend any time doing that. After all CTR is mostly dead. If Mozilla would have allowed this in Firefox like they did with Thunderbird, I might have ported a light version of CTR already back then, like happened with "CustomizeMyBird" for Thunderbird.

**Comment by Peacock365** [comment]
It seems like

**Comment by Aris-t2** [comment]
If Waterfox 68 will still support overlay add-ons, CTR will not die and won't need to be revived. ;-)

No need to reopen the thread. I will still receive notification, if you post something here.

**Comment by Peacock365** [comment]
The Waterfox 68 Alpha build should soon appear, hopefully CTR 2.0 is going to happen. I rely on it, and really hope it sees the light of the day.

**Comment by Aris-t2** [comment]
Lets see what happens in WF68. Maybe CTR will work right away.

**Comment by kn-yami** [comment]
It will not work out of the box, because Waterfox 68 will require a webex-like manifest for overlay extensions.

---
BTW thanks for making this extension. I use it every day on Basilisk.

**Comment by Aris-t2** [comment]
If required changes will only be reduced to rewriting/changing the manifest, I will update it.
