### ISSUE TITLE
Restore the option "add-on manager version number".

### ISSUE THREAD

**Issue by XX-J** [Aris-t2/ClassicThemeRestorer#408]
Please, restore the option "add-on manager version number".
I need this option in my Firefox. Because Basilisk and Waterfox don't run on Windows XP.

**Comment by Aris-t2** [comment]
Install a CTR version, that offer the option, and don't update it. ;-)
https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.7.3

**Comment by XX-J** [comment]
I maked this himself: [Classic Theme Restorer v1.7.9.xpi](http://ge.tt/1SOy1Hw2) from CTR_v1.7.8.2019.02.26.xpi
