### ISSUE TITLE
CTR_v1.7.8.2019.02.26.xpi

### ISSUE THREAD

**Issue by T3rM1nat0Rr** [Aris-t2/ClassicThemeRestorer#409]
Not a major issue, but after installing CTR_v1.7.8.2019.02.26.xpi, the extension information under "Add-ons>More" shows "Classic Theme Restorer 1.7.8.2019.02.10".
The problem appears to be that install.rdf still shows "<em:version>1.7.8.2019.02.10</em:version>" on the eighth line of its code.

**Comment by Aris-t2** [comment]
Most likely I forgot to update the string. Done now.
