### ISSUE TITLE
Can not change feed-button icon by CSS rule.

### ISSUE THREAD

**Issue by Cye3s** [Aris-t2/ClassicThemeRestorer#41]
I try to add this code to Stylish to change the RSS icon on URL bar:
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
#feed-button .toolbarbutton-icon {
list-style-image:url("chrome://browser/skin/places/livemark-item.png") !important;
-moz-image-region:rect(0 16px 16px 0) !important;
}

But did not work (Windows 7, Firefox 37.0.2, Classic Theme Restorer 1.3.1.1)

**Comment by Aris-t2** [comment]
The css rule is too weak to override CTRs default rule. Try this incl. AGENT_SHEET line in Stylish:

/*AGENT_SHEET*/
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
#urlbar #urlbar-icons #feed-button .toolbarbutton-icon {
list-style-image:url("chrome://browser/skin/places/livemark-item.png") !important;
-moz-image-region:rect(0 16px 16px 0) !important;
}

**Comment by Cye3s** [comment]
Thanks! 
It works well.
