### ISSUE TITLE
[Waterfox] Tab bar buttons disappear with "inverted icons" option enabled

### ISSUE THREAD

**Issue by EternityEngine** [Aris-t2/ClassicThemeRestorer#410]
I am running Waterfox 56.2.11 and CTR 1.7.8 on Windows 7. When I enable inverted icons for the tabs toolbar in CTR (General UI > Page 5 > Inverted icons), the navigation icons disappear from the tabs toolbar (the ones for when there are too many tabs to show all at once). This does not happen with my install of Firefox ESR 52.9.0. I also tested with the CTR 2019 preview in Waterfox, which did not fix the issue. I've attached comparison screenshots and my settings.

![waterfox_ctr_issue_disabled](https://user-images.githubusercontent.com/20052973/60764606-c6321480-a041-11e9-84df-02fba56beafa.png)
![waterfox_ctr_issue_enabled](https://user-images.githubusercontent.com/20052973/60764607-c8946e80-a041-11e9-993c-9222ddf24e78.png)
![waterfox_ctr_issue_ff](https://user-images.githubusercontent.com/20052973/60764608-c9c59b80-a041-11e9-9ba9-95eaa7d2a133.png)
[CTRpreferences.txt](https://github.com/Aris-t2/ClassicThemeRestorer/files/3365322/CTRpreferences.txt)

**Comment by Aris-t2** [comment]
Some CSS targets pointed to non-existent files. Latest preview should fix (some?) of them...

**Comment by EternityEngine** [comment]
Thank you, it works now.

![waterfox_fixed](https://user-images.githubusercontent.com/20052973/60781534-bc6ae880-a0f7-11e9-8d48-a5cf379d6d49.png)
