### ISSUE TITLE
[Waterfox] GlassMyFox ghost artefacts after hovering

### ISSUE THREAD

**Issue by Cicero-Interactive** [Aris-t2/ClassicThemeRestorer#413]
I know this is the repository for CTR, however, I couldn't find any other way to contact you (MozillaZine didn't let me register).
From what I read you won't update GMF anymore, but this here doesn't require much work I guess.

I've already reported and explained it in this issue in the Waterfox repository, but I didn't get any answers: https://github.com/MrAlex94/Waterfox/issues/904

Would it be possible to fix this little appearance problem?

**Comment by Cicero-Interactive** [comment]
Also, when already speaking of GMF appearance issues, here is one, too: https://github.com/MrAlex94/Waterfox/issues/906

This can be circumvented by the 2-line CSS code from the first comment, but this should should be set as default in my opinion

**Comment by Aris-t2** [comment]
I'm sorry, all my add-ons are discontinued and not on AMO anymore.

**Comment by Cicero-Interactive** [comment]
So you won't fix them no matter what? If so, can you at least open-source them? Many people still use these add-ons, and it would be a pity if we can't get them updated anymore

**Comment by Aris-t2** [comment]
Get all my AMO add-ons from here: https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.7.3

They are open source, xpi files are zip files, just rename them.

**Comment by Cicero-Interactive** [comment]
Oh, I didn't know that... But what's the point then paying for premium add-ons, when you can literally edit the source code? Or is there an option to encode it? 🤔

**Comment by Aris-t2** [comment]
Wait what, where do you pay for "premium" add-ons? My add-ons were always free. The optional Paypal link was for people who wanted to support me.

Unpack the xpi file, change the code the way you want it, compress it to a zip file and install it into your application.
