### ISSUE TITLE
Can be added support for Overlays?

### ISSUE THREAD

**Issue by timur-g** [Aris-t2/ClassicThemeRestorer#417]
First to say that I don't know what Overlays really is and whether it can fit to CTR scope, but my question is: can be added support for Overlays?
Example are extension export addons that don't work in Waterfox. 

ExtExp says in https://realityripple.com/Software/Mozilla-Extensions/ExtExp/ :
"Mozilla has dropped support for Overlays, which ExtExp relies on to function. There will be no further support for Firefox beyond v50.*. "

Or only solution is: https://github.com/MrAlex94/Waterfox/wiki/Engage-the-new-overlay-loader

**Comment by Aris-t2** [comment]
CTR can not "restore" overlays, it uses them itself (https://github.com/Aris-t2/ClassicThemeRestorer/blob/master/xpi/chrome.manifest#L38) what is one of the main reasons CTR is not working on Fx 57+ and was discontinued.
