### ISSUE TITLE
New tab from bookmark and on search, next to current on

### ISSUE THREAD

**Issue by timur-g** [Aris-t2/ClassicThemeRestorer#418]
I use CTR Old search with "open in new tab" and it's great. 
What's missing for that is a further customization "open next to current tab". 
That option could be useful for a new tab from search (in already existing "Search tab" part of UI) but more useful for a new tab from "open link in a new tab".
I see "Insert related tab after current tab" in Tab section but it doesn't do this. 

I also miss an option to open a new tab for a click from bookmark. It's also low priority because Ctrl will do it. And also a new tab from typing or pasting in URL bar. 

I used those options from TabMixPlus but CTR seems to be able to include them, so TMP wouldn't be needed in my case.

**Comment by Aris-t2** [comment]
The "old search" uses browsers internal "open in new tab" option `browser.search.openintab`.
Same applies to `browser.urlbar.openintab`.

Also look into `browser.tabs.insertAfterCurrent` and `browser.tabs.insertRelatedAfterCurrent` settings and set them the way you like.

You can also use middle click on bookmarks to open them in a new tab.

Like TMP CTR is not getting further developed anymore.

**Comment by timur-g** [comment]
Thank you. 
Just to note that in about:config of Waterfox Classic I don't see browser.urlbar.openintab nor browser.tabs.insertAfterCurrent

**Comment by Aris-t2** [comment]
Didn't know that. Did not test Waterfox Classic that much yet. Seems like those setting have been added somewhere later in Fx6x versions.

Maybe this helps https://addons.mozilla.org/addon/open-tabs-next-to-current/
According to AMO it works with Fx51+, so Waterfox Classic should be covered.

Older versions of these two might also help:
https://addons.mozilla.org/addon/new-tab-from-location-bar/
https://addons.mozilla.org/addon/open-in-new-tab-domain/

**Comment by timur-g** [comment]
Thank you, I'll close this.
