### ISSUE TITLE
Replace new Icon in Taskbar of Waterfox classic to avoid the red classic

### ISSUE THREAD

**Issue by guru1d** [Aris-t2/ClassicThemeRestorer#421]
It is not an issue, but request: Is it possible to switch the icon to the old design in taskbar?

Somehow I cannot stand to have the red "classic" in the new logo.

Thank you.

**Comment by Aris-t2** [comment]
Add-ons can not change the taskbar icon of an application. You have to use a different software to hack/change exe files embedded icons (and this has to be repeated after every update.)

**Comment by guru1d** [comment]
I see. Thank you for the fast reply.
