### ISSUE TITLE
CTRL+D Doesn't give a PopUp window as it did in FF48

### ISSUE THREAD

**Issue by FFnewbie** [Aris-t2/ClassicThemeRestorer#422]
I used magnificent CTRL+D to simply open the little window and see immediately the text string of a website title header and then I could quickly copy the text for my needs. Now using CTR this massively useful little Make a Bookmark window does not pop up. Instead it quietly saves a bookmark, which is useless. I want to be in complete control. 

How to get this Make a Bookmark popup back?   There must be something in CTR to cause it to remain hidden, because if I rename to __chrome or install a brand new FF 75, this feature works flawlessly, although in FF 75 the tiny window has been changed to an arse-ugly abomination. The revered and beloved maker of DORANDO KEYCONFIG addon [discontinued since] has said that Mozilla devs are on a self-destructive path. I fully agree. I had to spend at least four friggin days, until I MADE FF look like FF48 again.. (almost.)

![FF75_looking_lik_FF48_again](https://user-images.githubusercontent.com/64174646/80423220-ed631680-88df-11ea-9c3f-8602386a9ece.png)

**Comment by Aris-t2** [comment]
CTR offers an option to control this. You might have triggered it:

![123](https://user-images.githubusercontent.com/6013569/80453396-730ab480-8928-11ea-8abd-14a856a6c88c.png)
