### ISSUE TITLE
CSS file: identitybox_padlock icon hidden disables CTRL+D in FF 75

### ISSUE THREAD

**Issue by FFnewbie** [Aris-t2/ClassicThemeRestorer#423]
Found what disabled CTRL+D in FF75!
**identitybox_padlock_icon_hidden.css**
When I commented this line out in userChrome.css, CTRL+D works again!!!!

**Comment by Aris-t2** [comment]
Looks like you are in the wrong repository. CTR does not even have a `identitybox_padlock_icon_hidden.css` file. Most likely you wanted to post in the general thread of https://github.com/Aris-t2/CustomCSSforFx

Anyways, `identitybox_padlock_icon_hidden.css` is disabled by default. Good to know it has side effects.
