### ISSUE TITLE
Enter Read View icon is not present

### ISSUE THREAD

**Issue by luuuciano** [Aris-t2/ClassicThemeRestorer#48]
When Classic Theme Restorer is active, it is not showed the Read View toggle icon.
![readview](https://cloud.githubusercontent.com/assets/6766551/8021964/0b03e38e-0c8c-11e5-9539-65c3b16d9754.png)

(in the screenshot it was deactivated, to show the icon...)

**Comment by luuuciano** [comment]
OH MY GOD...... I can see it now! it is a MIRACLE! (?)

(maybe I needed to disable/enable it? no idea.....)

**Comment by Aris-t2** [comment]
The icon only appears on pages that offer reader mode, not on all of them. 
CTR does not modify button appearance by default, it only gets moved to the left, if you are using star or feed button in location bar options.
