### ISSUE TITLE
Squared Tabs don't work when Firefox Developer Edition is running

### ISSUE THREAD

**Issue by AdrianoCahete** [Aris-t2/ClassicThemeRestorer#54]
If i change to squared tabs (Classic) when two Firefoxes are running (v39 and Developer Edition with different profiles, but Sync on), the Default Fx (v39) don't change tabs layout.
It change everything, tabs position included, but not styles. Sometimes bugs and show some of two styles (default and squared, default on rounded sides, but squared in click area).

CTR v1.3.5-b3 (previously stable version, but i tried to update to see if is working), Fx 39.
If you need more info, please tell me.

**Comment by Aris-t2** [comment]
This is a Firefox bug.

Please check whether the browser.devedition.theme.enabled preference in about:config got switched to true. You can also use CTRs prefwindow advanced tab to disabled that preference.

**Comment by AdrianoCahete** [comment]
Hm... I dind't know that.

Works when i changed that key in DevEdition, back to v39 change theme to any, then changed back to default.

Thank you. :)
