### ISSUE TITLE
Tabbar height issue with e10s enabled and a tab crashes on Nightly

### ISSUE THREAD

**Issue by rn10950** [Aris-t2/ClassicThemeRestorer#59]
I have an issue with e10s enabled. When a tab crashes, the tabbar height increases from 28px to 31px. 
![ctr-e10sbug](https://cloud.githubusercontent.com/assets/8262801/8863238/d93481a8-3164-11e5-9f24-aafc6bf7b498.PNG)

**Comment by Aris-t2** [comment]
Is there any tab add-on you are using, that could add a "height" value like seen on your screenshot?

By default tabbrowser-tabs node does not have a "height" attribute.

![1](https://cloud.githubusercontent.com/assets/6013569/8864185/603a8d02-319f-11e5-9294-6b384abe7655.png)

How to force a tab crash?

**Comment by rn10950** [comment]
The height attribute is not shown in DOM Node view of the inspector, you have to click the views button and switch to computed styles.

![domi](https://cloud.githubusercontent.com/assets/8262801/8865931/5899c40c-3184-11e5-9f5a-40bb423cc599.PNG)

How I force a tab to crash is load a page with Flash, open up Windows Task Manager and switch to "Processes" tab. Find "plugin-container.exe" right-click and kill it.

![pc-process](https://cloud.githubusercontent.com/assets/8262801/8865976/c14f255a-3184-11e5-915d-4a4c58cef139.PNG)

This should kill the Flash container and therefore crash the tab. There may be an easier way to do this, but this is how I know how to do it.

**Comment by Aris-t2** [comment]
Thanks, I completely forgot about the flash container. 
Glitch will be fixed on next beta.

**Comment by Aris-t2** [comment]
Fixed on 1.3.6 beta 6.
