### ISSUE TITLE
Maybe remove " (Customize UI)" from title

### ISSUE THREAD

**Issue by scootergrisen** [Aris-t2/ClassicThemeRestorer#60]
Instead of calling this add-on for "Classic Theme Restorer (Customize UI)" would it not be better to call it "Classic Theme Restorer"?

Also when you deactivate an add-on in Firefox it puts "(disabled)" at the end of the title so it becomes:
"Classic Theme Restorer (Customize UI) 1.3.5 (disabled)" which don't look so nice with the double () ().

**Comment by Aris-t2** [comment]
"(Customize UI)" was not always present, but you are right it should be removed.

**Comment by Aris-t2** [comment]
"(Customize UI)" is now gone from AMO and on current 1.3.9 betas. Once 1.3.9 becomes final that string will be gone for everybody.
