### ISSUE TITLE
Tab separators missing from australized squared tabs

### ISSUE THREAD

**Issue by Poorchop** [Aris-t2/ClassicThemeRestorer#63]
I'm not sure how long this has been present but I just noticed this after upgrading to Windows 10, which forces the use of white title bars on all windows. The black tab separators are visible with the default curved tabs, but they're missing when switching to the "squared tabs (australized)" option.

![untitled](https://cloud.githubusercontent.com/assets/5256208/9048050/25450782-3a04-11e5-86f0-bda5b415deae.png)

Windows 10, Firefox 39.0

**Comment by Aris-t2** [comment]
Tab seperators were never present when using  "squared tabs (australized)" option. Add the following code to a Stylish style to restore them.

```
/*AGENT_SHEET*/
#main-window #navigator-toolbox #TabsToolbar #tabbrowser-tabs[movingtab] > .tabbrowser-tab[beforeselected]:not([last-visible-tab])::after,
#main-window #navigator-toolbox #TabsToolbar .tabbrowser-tab:not([visuallyselected]):not([afterselected-visible]):not([afterhovered]):not([first-visible-tab]):not(:hover)::before,
#main-window #navigator-toolbox #TabsToolbar #tabbrowser-tabs:not([overflow]) > .tabbrowser-tab[last-visible-tab]:not([visuallyselected]):not([beforehovered]):not(:hover)::after,
#main-window #navigator-toolbox #TabsToolbar #tabbrowser-tabs[movingtab] > .tabbrowser-tab[beforeselected]:not([last-visible-tab])::after,
#main-window #navigator-toolbox #TabsToolbar .tabbrowser-tab:not([selected]):not([afterselected-visible]):not([afterhovered]):not([first-visible-tab]):not(:hover)::before,
#main-window #navigator-toolbox #TabsToolbar #tabbrowser-tabs:not([overflow]) > .tabbrowser-tab[last-visible-tab]:not([selected]):not([beforehovered]):not(:hover)::after {
  mbackground-image: url(chrome://browser/skin/tabbrowser/tab-separator.png) !important;
  opacity:1.0 !important;
}
```

**Comment by Poorchop** [comment]
Thank you. There's a typo on line 8 where you have an extra "M" before `background-image` but otherwise it works. For some reason, I thought that this would make it easier to discern the current tab from background tabs, but it didn't make a difference to my eyes. Nevertheless, thanks for the solution and for your work on this add-on in general.
