### ISSUE TITLE
Extension shows as unsigned under FF 39.0.3

### ISSUE THREAD

**Issue by wohali** [Aris-t2/ClassicThemeRestorer#65]
With the recent announcement of https://wiki.mozilla.org/Addons/Extension_Signing I did an audit of all of my extension. Only this extension and UBlock Origin showed up as unsigned. Can this be resolved prior to the release of the next FF update?

**Comment by Aris-t2** [comment]
This must be a Firefox bug or glitch in your profile. All CTR beta and final builds are signed, if you install them from add-ons.mozilla.org.
