### ISSUE TITLE
Bookmark icon messed up in small buttons mode in Firefox 40

### ISSUE THREAD

**Issue by Poorchop** [Aris-t2/ClassicThemeRestorer#66]
Bookmark icon is scrunched up after upgrading to Firefox 40:

![untitled](https://cloud.githubusercontent.com/assets/5256208/9228127/0b26814a-40e5-11e5-802c-4fc320afdbc9.png)

For quick reference, here's how it looks normally:

![untitled1](https://cloud.githubusercontent.com/assets/5256208/9228172/47957f64-40e5-11e5-8922-3213b5037115.png)

**Comment by Aris-t2** [comment]
Win10 + small button view, right?
Next build (1.3.8beta1) will fix this.

**Comment by Poorchop** [comment]
Yup. Thank you for the heads up.
