### ISSUE TITLE
Can't click minimize, close... button

### ISSUE THREAD

**Issue by yuyuvn** [Aris-t2/ClassicThemeRestorer#68]
From firefox 40, it seem window buttons is behind the toolbar.
![capture](https://cloud.githubusercontent.com/assets/6410496/9292285/312732b8-4419-11e5-9a66-fc4fd45aac5c.PNG)
Here is my settings:
![capture2](https://cloud.githubusercontent.com/assets/6410496/9292286/316e7c86-4419-11e5-90ff-f42d03f15a63.PNG)

I think you should add an option to change margin value of each toolbar

**Comment by Aris-t2** [comment]
Tell me a bit more about your configuration.
Is this Windows 10 (yes/no)?
OS theme (default one or not, modified or not)?
Firefox lw-theme (yes/no; if yes, which one)?
CTR version (latest final or beta)?
Which CTR settings are you using (does this happen with default ones)?
....

Margin values for toolbar would only break the ui in most cases.

**Comment by yuyuvn** [comment]
Yeah, I using "Tabs not on top v2" but with v1, it become 2 lines like this:
![capture](https://cloud.githubusercontent.com/assets/6410496/9292684/988b49ea-4431-11e5-8244-6362ce6aaea7.PNG)

* Yes, this is windows 10
* OS theme: default 
* Firefox default theme, in my screenshot is this theme https://addons.mozilla.org/en-US/firefox/addon/transparent-187109/?src=ss
* Firefox version 40.0.2
* CTR 1.3.7.1
* My settings:
```
CTR_Preferences__DO_NOT_EDIT__'='->booleans__':'->strings__'~'->integers
nbiconsize:small
bmbutpanelm=false
noconicons=false
nav_txt_ico:icons
ctabtsh:#FFFFFF
tabmokcolor2=false
tabtextc_def=false
combrelstop=false
ctabheightcb=false
alttabstb2=true
mbarposition:toolbar-menubar
cntab2:#007700
fsaduration=true
alt_newtabp=false
alt_addonsm=false
hidezoomres=true
tabcolor_pen=false
menubarnofog=false
iat_notf_vt=false
ctabact1:#FF8800
tabcolor_hov=false
ctabpent:#000000
cuibuttons=true
cappbutc1:#00FF00
menubarfs=false
starinurl=true
hidesbclose=false
invicoextrabar=false
ctabunr2:#007700
tabmokcolor4=false
hidetbwot=false
hightabpososx=false
nonavbarbg=true
appmenuitem=true
icopageinfo=false
ctabpen2:#007700
extraurlkeycb=false
altabico:altabico_white
invicotabsbar=false
bf_space=false
cappbutc2:#007700
dblclnewtab=false
tabtextsh_act=false
padlockex=true
cntabhov2:#FFFF00
highaddonsbar=false
tabfbold_unr=false
ctab1:#00FF00
appbuttontxt:
statusbar=true
hideprivmask=true
altmenubar=false
nonavborder=true
contextitem=false
tabtextsh_hov=false
closetab:closetab_default
ctabunr1:#00FF00
tabtextc_pen=false
nonavtbborder=false
addonversion=false
appbutton:appbutton_v2io2
appbuttonc:appbuttonc_orange
appbutmhi=false
mbarpositionl:toolbar-menubar
ctabheight~28
altmenubarpos2=false
smallnavbut=false
ctabact2:#FF0000
ctabpen1:#00FF00
tbsep_winc=false
feedinurl=true
invicobookbar=false
hidetbwote2=true
nbcompact=false
noemptypticon=false
ntabcolor_hov=false
alttabstb=false
ctabactt:#000000
backforward=true
activndicat=false
tabc_hov_unl=false
notabbg=true
tabcolor_act=false
ctabunrt:#000000
appbclmmenus=false
ctabunrtsh:#FFFFFF
dblclclosefx=false
verifiedcolors=true
pmhidelabels=false
ctabwidth~250
ctabhovt:#000000
closetabhfl=false
tabs:tabs_squared
closeicon:closeicon_default
closeabarbut=false
inviconavbar=false
tabtextc_unr=false
skipprintpr=false
tabfbold_pen=false
hidenavbar=false
addonbarfs=false
tabtextsh_pen=false
hide_bf_popup=false
urlbardropm=false
panelmenucol=false
tbconmenu=false
nbisizedelay~0
ctabt:#000000
tabcolor_unr=false
bfurlbarfix=false
menupopupscr=false
tabc_act_tb=false
tabcolor_def=false
tabmokcolor3=false
tabc_hov_unr=false
emptyfavicon2=false
tabfita_pen=false
ctabacttsh:#FFFFFF
throbberalt=false
altmenubarpos=false
padlock:padlock_default
findbar:findbar_bottoma
ctabhovtsh:#FFFFFF
alt_addonsp=false
tabtextc_hov=false
invicoaddonbar=false
tabtextc_act=false
nodevtheme2=false
tabtextsh_unr=false
bmbutnotext=false
tabfbold_hov=false
mbarforceleft=false
tabfbold_act=false
noaddonbarbg=false
toolsitem=true
ctabpentsh:#FFFFFF
chevronfix=false
svgfilters=false
tabfita_act=false
ctab2:#007700
tabmokcolor=false
closeonleft=false
aerocolors=false
faviconurl=true
cntabhov1:#FFFFBB
bmanimation=true
notextshadow=false
invicomenubar=false
ctabhov1:#FFFFBB
wincontrols=false
ctabmwidth~100
bmarkoinpw=false
noresizerxp=false
nobookbarbg=true
square_edges=false
cpanelmenus=true
puictrbutton=false
anewtaburl:about:newtab
ctabhov2:#FFFF00
appbutbdl=false
mbarforceright=false
e10stab_notd=false
emptyfavicon=true
hideurelstop=false
anewtaburlcb=false
tabfita_unr=false
athrobberurl:
notabfog=false
tabfita_hov=false
tabfbold_def=false
tabtextsh_def=false
hidetbwote=true
tabsontop:false2
am_extrabars~0
hideurlgo=false
tabfita_def=false
pananimation=true
cntab1:#00FF00
ntabcolor_def=false
hideprbutton=false
```

**Comment by yuyuvn** [comment]
When I insert ```#nav-bar { margin-right: 140px; margin-left: 30px }``` to userChrome.css, it work well:
![capture](https://cloud.githubusercontent.com/assets/6410496/9292698/5ee3f376-4432-11e5-993f-3ef95552a4ac.PNG)

**Comment by Aris-t2** [comment]
This was supposed to be like that, but I will try to add some tweaks to catch that case without breaking the appearance it was actually made for.

**Comment by Aris-t2** [comment]
CTR 1.4.0 beta 1 offers an option to set custom left and right navigation toolbar paddings:
https://addons.mozilla.org/addon/classicthemerestorer/versions

This should resolve your issue.

**Comment by yuyuvn** [comment]
Sorry for answer late.
I think it should be margin instead of padding, it still overlap with window controls.

**Comment by Aris-t2** [comment]
It overlaps when the option is enabled too? Can you add another screenshot?

**Comment by yuyuvn** [comment]
<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/6410496/11245805/2a1ebaea-8e47-11e5-9e83-36baaf1b55d9.PNG">
Here is my config
Still can't click click minimize, close... button

**Comment by Aris-t2** [comment]
You are right about it not working with padding. The strange thing is it worked back then when I added this option. Next beta will switch to margin ;-).

**Comment by Aris-t2** [comment]
CTR 1.4.4b2 https://addons.mozilla.org/addon/classicthemerestorer/versions now offers another set of related sub options. The first one only targets padding of navigation toolbar customizable content. The second one is the more interesting in your case. It changes the left and right margin of navigation toolbar.
![1](https://cloud.githubusercontent.com/assets/6013569/11300977/a4ad13c2-8f93-11e5-9c54-5ff3fcf3a2c7.png)

**Comment by yuyuvn** [comment]
it worked. thanks
