### ISSUE TITLE
Checkbox to disable cursor focus being placed in URL bar when using custom new tab page

### ISSUE THREAD

**Issue by alice-margatroid** [Aris-t2/ClassicThemeRestorer#78]
Right now when you use custom new tab page the cursor focus will be move into the URL bar.

This adds extra clicks / keystrokes to the workflow when you just want to CTRL+T and type into the textarea field of the website that just loaded.

**Comment by Aris-t2** [comment]
The already is an add-on on AMO to achieve that.

https://addons.mozilla.org/addon/custom-new-tab/

**Comment by alice-margatroid** [comment]
There are a lot of addons on AMO that can do what CTR does. That is a weird argument fornot implementing a classic feature in an addon that calls itself classic theme restorer. But I guess there is nothing to change your mind.

**Comment by Aris-t2** [comment]
Maybe in the future.

**Comment by alice-margatroid** [comment]
Thank you for considering it. Hope for your good will is all I have.
