### ISSUE TITLE
When CTR is enabled, main toolbar doesn't have enough right-padding

### ISSUE THREAD

**Issue by BoffinbraiN** [Aris-t2/ClassicThemeRestorer#81]
Using Firefox 40.0.1, and the default theme, the menu button looks like this:

![good-spacing](https://cloud.githubusercontent.com/assets/13255058/9701040/15bb6cd0-5411-11e5-8a79-39e967bd89db.png)

When CTR is enabled (1.3.8), it looks like this:

![bad-spacing](https://cloud.githubusercontent.com/assets/13255058/9701044/211def9e-5411-11e5-95b6-53b38ff3d9a9.png)

I don't think any of CTR's options affect this issue. I'm currently using the following CSS as a workaround:

    #nav-bar {
      padding-right: 3px;
    }

**Comment by Aris-t2** [comment]
On default view the menu button is outside the navigation toolbar customization container and is not movable. CTR moves a clone of it into the customizable area. Doing this the button becomes a default toolbar button with default left/right margins/paddings.

Compare the left padding/margin between window border and first toolbar button on navigation toolbar, if you move a default toolbar button to navigation toolbar buttons first position (e.g. downloads or home button) with the right one.
The space matches the one CTR offers for the last button on navigation toolbar (-> menu button in your case).

**Comment by BoffinbraiN** [comment]
That makes sense. I can confirm that any toolbar buttons moved to the left edge of the navigation toolbar also don't have enough padding, whether CTR is enabled or not. I don't usually have anything there, but I can imaging that being an issue for some users.

Is there any way you can provide an option in CTR to compensate for these padding issues? Even something as simple as a checkbox that manually applies left and right padding to the nav-bar when checked? It's possible that the left-padding issue might get fixed in future versions so it makes sense to make it an optional feature.

**Comment by Aris-t2** [comment]
It is of course possible to add such an option, but as far as I can see the left/right navigation toolbar padding was like this even before Fx29 changed the ui.

This is the best solution, if using CTR:

```
#nav-bar-customization-target {
  padding-left: 3px !important;
  padding-right: 3px !important;
}
```

**Comment by BoffinbraiN** [comment]
Yep, that's pretty much what I had. Is there no chance of it making it into the options, then? Or perhaps an option to *not* pull the menu button out of its special fixed container if we just want to use CTR for styling tabs?

**Comment by Aris-t2** [comment]
I will add an option for navigation toolbars left and right paddings in CTR 1.4.0.
Version 1.3.9 is almost ready to go online and I won't get new options/features.

The way Mozilla designed and implemented the "menu button" leaves no room for making its CTR changes optional. Either it is not movable at all or like now in CTR and I think it is way better to keep it (re)movable. Many people incl. myself prefer using the "appbutton on titlebar" designed for Desktop users over using a "button menu with huge buttons" designed for mobile devices.

**Comment by BoffinbraiN** [comment]
Thanks for taking my feedback onboard. :) I look forward to seeing it integrated in the future.

**Comment by Aris-t2** [comment]
CTR 1.4.0 beta 1 offers an option to set custom left and right navigation toolbar paddings:
https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by BoffinbraiN** [comment]
Works for me! Good job.
