### ISSUE TITLE
Allow replacing of Windows 10 styled window buttons with native ones

### ISSUE THREAD

**Issue by RibShark** [Aris-t2/ClassicThemeRestorer#82]
As you know, Firefox 40 contains various tweaks designed to make the browser look better in Windows 10. Unfortunately if a custom theme for window borders is used, these tweaks make Firefox look very ugly compared to other windows. The option "Title/menu/tabs toolbar: remove window color (Windows 10" partially fixes this, but the window buttons (minimise, maximise, close) keep using Firefox's non-native style. Would it be possible to replace these with the native window buttons found on older (<=39) versions of Firefox or Firefox 40 on other Windows versions?

**Comment by Aris-t2** [comment]
It "would" be possible in theory, but this is what every third party OS theme user has to achieve by herself/himself. There is no way I can add buttons for every third party OS theme for every possible case (especially non-default DPI or even HiDPI values).

However I will add an option to remove the "default" OS min/max/close buttons currently visible, if using  "Title/menu/tabs toolbar: remove window color (Windows 10)" option with third party themes.
