### ISSUE TITLE
[v1.4.0beta3] Problem if Tabtitle in Titlelist is activated with long Titles

### ISSUE THREAD

**Issue by Alpengreis** [Aris-t2/ClassicThemeRestorer#92]
Hello

First, thank you very much for this GREAT addon!

I have a problem (with v1.4.0beta3), if Tabtitle in Titlelist is activated with long Titles such as in the following example ...

![ctr-problem0](https://cloud.githubusercontent.com/assets/11355601/9942277/802bc138-5d7a-11e5-9102-910df1d47cc6.JPG)
![ctr-problem1](https://cloud.githubusercontent.com/assets/11355601/9942284/88e4fa92-5d7a-11e5-9927-268436f52d8a.JPG)
![ctr-problemok](https://cloud.githubusercontent.com/assets/11355601/9942297/8ee5c5f2-5d7a-11e5-9117-9167a91e9a42.JPG)

.. then the hole right side is truncated.

Maybe it would be good to have a configurable max length and the rest could be showed with as hovered or scrollable text or something like that.

Greetings
*Alpengreis*

**Comment by Aris-t2** [comment]
I will fix this on next beta.

Text length in titlebar will automatically be reduced in such cases.

**Comment by Alpengreis** [comment]
Sounds good, thank you very much!

**Comment by Alpengreis** [comment]
Fixed in v1.4.0beta4 - thanks!
