### ISSUE TITLE
Small bug in Squared Tabs Classic v.2 theme

### ISSUE THREAD

**Issue by supraspecies** [Aris-t2/ClassicThemeRestorer#95]
There's a small bug in Squared Tabs Classic v.2 theme. Tabs go 1-2 pixels below the tab bar. It's a minor, but a very annoying glitch for me. I posted a screenshot.

http://s29.postimg.org/xne9sv4rb/Untitled_1.jpg

Could you please fix this? And preferably tell me what to adjust in "tabs_squaredc2.css" file (supposedly it's this file) to get rid of the issue asap, as I'm about to compile my customized version of Firefox.

Thank you for all the effort and a great extension.

**Comment by supraspecies** [comment]
Another issue with the same tab theme. Screenshot is taken from my Windows 7 computer this time.

http://s27.postimg.org/vlar8zpk3/issue_2.jpg

To the left is Squared Tabs Classic v.1. To the right is v2. As you can see, v.2 adds a lot of unused space. Would be great if it could be removed. Thank you. And again, if you can provide a CSS code to quickly fix the issue, that would be appreciated.

**Comment by supraspecies** [comment]
And another glitch. If you add New Tab "+" button at tyhe end of the last tab in tab row (I did it via userChrome.css), then with Squared Tabs Classic v.2 and lots of open tabs, the tabs overlay the "+" button. That doesn't happen with Squared Tabs Classic v.1 theme.

**Comment by Aris-t2** [comment]
I will fix the glitch where tabs overlap with navigation toolbar on next CTR beta.

To reduce the gap at tab toolbars end in maximized mode for squared tabs v2 use this code in Stylish:
```
/*AGENT_SHEET*/
#main-window[sizemode="maximized"] #TabsToolbar {
  -moz-margin-end: -20px !important;
}
```
Tab toolbar dimensions do not get altered for squared tabs v2 in that case and match the default ones.

Not sure about the new tab "+" issue. Does it happen, if you switch to "default curved" tabs too?
If not, post a screenshot and the code you are using.

**Comment by supraspecies** [comment]
Oh, sorry, didn't realize you answered to e-mail instead of GitHub. Yes,
tabs overlay "+" button even in default theme. So it's not related to CTR
in any way, I understand. Thank you very much for your support.

**Comment by supraspecies** [comment]
Just tried the code, editing theme CSS files directly (I don't use Stylish and I see no reason to install an extension I don't use). Everything works perfect. I made a few more adjustments to the code to remove absolutely all gaps in tab bar by example in Squared Tabs Classic v.1 theme. Now everything is perfect. Thank you very much for pointing me in the right direction and showing me how do it! The rest was easy to figure out.

Here's the complete code I use to remove all gaps:

/*AGENT_SHEET*/
#main-window[sizemode="normal"] #TabsToolbar {
  -moz-margin-end: -20px !important;
}
#main-window[sizemode="maximized"] #TabsToolbar {
  -moz-margin-end: -20px !important;
}
#TabsToolbar:not([currentset*="tabbrowser-tabs,new-tab-button"]):not([orient="vertical"]) #tabbrowser-tabs:not([overflow]) {
  -moz-margin-end: -15px !important;
}
/* remove gaps before and after tabs */
.tabbrowser-arrowscrollbox > .arrowscrollbox-scrollbox {
  -moz-padding-start: 0px !important;
}

This removes spaces after left "new tab" button, between tabs and arrow, and between arrow and minimize button. In fullscreen and windows mode. It's all your code. :) Again, thank you a lot!

**Comment by supraspecies** [comment]
Found another bug in the same theme (not related to my theme modifications, tried with original as well) - "List All Tabs" button is barely clickable when you use Windows Classic theme. Only clickable if you click the very right of it. Should happen in any OS, but I personally tested it in XP. Happens only in tab theme v.2, not in v.1.

CSS code to solve this would be appreciated, although I might figure it out myself now.

Thanks.

**Comment by Aris-t2** [comment]
Is "list all tabs" not clickable without your modifications?

**Comment by supraspecies** [comment]
Ok, forgive me - indeed my modifications are at fault. I forgot to reload Firefox after I did the testing. The problem is on my side, and I will figure it out. Again, thanks for your support and you can mark the topic as solved (or should I? I didn't find how to).

**Comment by Aris-t2** [comment]
Well, editing files manually has to be repeated after every update, right? Stylish css tweaks will stay after update, so that is the easiest way imo.

The bug you are referring to is related to Windows XP and to Windows classic visual styles on Windows Vista and 7. I have not found a clean solution for that yet.

**Comment by supraspecies** [comment]
Ah, yes, that's a very point. I will definitely look into Stylish then.
